// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fleetly/server/v1/database.proto

package serverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDatabaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 库实例名（^[a-z0-9][a-z0-9_-]*$——与 app 名同字符集规则；对象前缀族
	// fleetly-db-* 与 app 名族解耦，app 与库实例可重名）。
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 模板 ID（平台内置注册表：postgres-16 / redis-7；未知 → 400）。
	Template string `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	// 资源限额（零值字段回落模板缺省——PG 1C/1Gi、Redis 0.5C/256Mi）。
	Limits *DatabaseLimits `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`
	// 备份计划（零值字段回落平台缺省 24h/7 份/03:00 UTC）。
	BackupPlan    *DatabaseBackupPlan `protobuf:"bytes,4,opt,name=backup_plan,json=backupPlan,proto3" json:"backup_plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseRequest) Reset() {
	*x = CreateDatabaseRequest{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseRequest) ProtoMessage() {}

func (x *CreateDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseRequest.ProtoReflect.Descriptor instead.
func (*CreateDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDatabaseRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *CreateDatabaseRequest) GetLimits() *DatabaseLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *CreateDatabaseRequest) GetBackupPlan() *DatabaseBackupPlan {
	if x != nil {
		return x.BackupPlan
	}
	return nil
}

type CreateDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *DatabaseView          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseResponse) Reset() {
	*x = CreateDatabaseResponse{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseResponse) ProtoMessage() {}

func (x *CreateDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseResponse.ProtoReflect.Descriptor instead.
func (*CreateDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDatabaseResponse) GetDatabase() *DatabaseView {
	if x != nil {
		return x.Database
	}
	return nil
}

type GetDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseRequest) Reset() {
	*x = GetDatabaseRequest{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseRequest) ProtoMessage() {}

func (x *GetDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseRequest.ProtoReflect.Descriptor instead.
func (*GetDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{2}
}

func (x *GetDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *DatabaseView          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseResponse) Reset() {
	*x = GetDatabaseResponse{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseResponse) ProtoMessage() {}

func (x *GetDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseResponse.ProtoReflect.Descriptor instead.
func (*GetDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{3}
}

func (x *GetDatabaseResponse) GetDatabase() *DatabaseView {
	if x != nil {
		return x.Database
	}
	return nil
}

type ListDatabasesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 行数上限（缺省 100）。
	Limit         int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesRequest) Reset() {
	*x = ListDatabasesRequest{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesRequest) ProtoMessage() {}

func (x *ListDatabasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesRequest.ProtoReflect.Descriptor instead.
func (*ListDatabasesRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{4}
}

func (x *ListDatabasesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDatabasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Databases     []*DatabaseView        `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesResponse) Reset() {
	*x = ListDatabasesResponse{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesResponse) ProtoMessage() {}

func (x *ListDatabasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesResponse.ProtoReflect.Descriptor instead.
func (*ListDatabasesResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{5}
}

func (x *ListDatabasesResponse) GetDatabases() []*DatabaseView {
	if x != nil {
		return x.Databases
	}
	return nil
}

type DeleteDatabaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 破坏性确认 = 实例名原样回传（mismatch → 400——与卷-节点 409 前哨同
	// 型的数据安全面；引用 app 在册 → 409 E_DB_REFERENCED 先行）。
	Confirm string `protobuf:"bytes,2,opt,name=confirm,proto3" json:"confirm,omitempty"`
	// 删除数据卷（默认 false = 保留转 orphaned；true = 不可逆删除）。
	DeleteVolumes bool `protobuf:"varint,3,opt,name=delete_volumes,json=deleteVolumes,proto3" json:"delete_volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatabaseRequest) Reset() {
	*x = DeleteDatabaseRequest{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatabaseRequest) ProtoMessage() {}

func (x *DeleteDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatabaseRequest.ProtoReflect.Descriptor instead.
func (*DeleteDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteDatabaseRequest) GetConfirm() string {
	if x != nil {
		return x.Confirm
	}
	return ""
}

func (x *DeleteDatabaseRequest) GetDeleteVolumes() bool {
	if x != nil {
		return x.DeleteVolumes
	}
	return false
}

type DeleteDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatabaseResponse) Reset() {
	*x = DeleteDatabaseResponse{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatabaseResponse) ProtoMessage() {}

func (x *DeleteDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatabaseResponse.ProtoReflect.Descriptor instead.
func (*DeleteDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDatabaseResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteDatabaseResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SuspendDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendDatabaseRequest) Reset() {
	*x = SuspendDatabaseRequest{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendDatabaseRequest) ProtoMessage() {}

func (x *SuspendDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendDatabaseRequest.ProtoReflect.Descriptor instead.
func (*SuspendDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{8}
}

func (x *SuspendDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SuspendDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *DatabaseView          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendDatabaseResponse) Reset() {
	*x = SuspendDatabaseResponse{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendDatabaseResponse) ProtoMessage() {}

func (x *SuspendDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendDatabaseResponse.ProtoReflect.Descriptor instead.
func (*SuspendDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{9}
}

func (x *SuspendDatabaseResponse) GetDatabase() *DatabaseView {
	if x != nil {
		return x.Database
	}
	return nil
}

type ResumeDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeDatabaseRequest) Reset() {
	*x = ResumeDatabaseRequest{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDatabaseRequest) ProtoMessage() {}

func (x *ResumeDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDatabaseRequest.ProtoReflect.Descriptor instead.
func (*ResumeDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{10}
}

func (x *ResumeDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResumeDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *DatabaseView          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeDatabaseResponse) Reset() {
	*x = ResumeDatabaseResponse{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDatabaseResponse) ProtoMessage() {}

func (x *ResumeDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDatabaseResponse.ProtoReflect.Descriptor instead.
func (*ResumeDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{11}
}

func (x *ResumeDatabaseResponse) GetDatabase() *DatabaseView {
	if x != nil {
		return x.Database
	}
	return nil
}

type RetryDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDatabaseRequest) Reset() {
	*x = RetryDatabaseRequest{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDatabaseRequest) ProtoMessage() {}

func (x *RetryDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDatabaseRequest.ProtoReflect.Descriptor instead.
func (*RetryDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{12}
}

func (x *RetryDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RetryDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *DatabaseView          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDatabaseResponse) Reset() {
	*x = RetryDatabaseResponse{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDatabaseResponse) ProtoMessage() {}

func (x *RetryDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDatabaseResponse.ProtoReflect.Descriptor instead.
func (*RetryDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{13}
}

func (x *RetryDatabaseResponse) GetDatabase() *DatabaseView {
	if x != nil {
		return x.Database
	}
	return nil
}

type UpdateDatabaseSettingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 资源限额（零值字段回落模板缺省；limits 变更 = spec 重建由收敛器承载）。
	Limits *DatabaseLimits `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
	// 备份计划（备份调度执行体随 S5 票据；本面先行受理与展示）。
	BackupPlan    *DatabaseBackupPlan `protobuf:"bytes,3,opt,name=backup_plan,json=backupPlan,proto3" json:"backup_plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDatabaseSettingsRequest) Reset() {
	*x = UpdateDatabaseSettingsRequest{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatabaseSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatabaseSettingsRequest) ProtoMessage() {}

func (x *UpdateDatabaseSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatabaseSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateDatabaseSettingsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateDatabaseSettingsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDatabaseSettingsRequest) GetLimits() *DatabaseLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *UpdateDatabaseSettingsRequest) GetBackupPlan() *DatabaseBackupPlan {
	if x != nil {
		return x.BackupPlan
	}
	return nil
}

type UpdateDatabaseSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *DatabaseView          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDatabaseSettingsResponse) Reset() {
	*x = UpdateDatabaseSettingsResponse{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatabaseSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatabaseSettingsResponse) ProtoMessage() {}

func (x *UpdateDatabaseSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatabaseSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateDatabaseSettingsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateDatabaseSettingsResponse) GetDatabase() *DatabaseView {
	if x != nil {
		return x.Database
	}
	return nil
}

// DatabaseLimits 是资源限额（仅 limits——镜像/引擎参数受管）。
type DatabaseLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU 限额（核数；0 = 模板缺省）。
	CpuSeconds float64 `protobuf:"fixed64,1,opt,name=cpu_seconds,json=cpuSeconds,proto3" json:"cpu_seconds,omitempty"`
	// 内存限额（字节；0 = 模板缺省）。
	MemoryBytes   int64 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseLimits) Reset() {
	*x = DatabaseLimits{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseLimits) ProtoMessage() {}

func (x *DatabaseLimits) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseLimits.ProtoReflect.Descriptor instead.
func (*DatabaseLimits) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{16}
}

func (x *DatabaseLimits) GetCpuSeconds() float64 {
	if x != nil {
		return x.CpuSeconds
	}
	return 0
}

func (x *DatabaseLimits) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

// DatabaseBackupPlan 是备份计划（§5.4 配置键 databases.backup_* 的 per
// 实例覆盖；0 值字段 = 平台缺省）。
type DatabaseBackupPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntervalHours int32                  `protobuf:"varint,1,opt,name=interval_hours,json=intervalHours,proto3" json:"interval_hours,omitempty"`
	Keep          int32                  `protobuf:"varint,2,opt,name=keep,proto3" json:"keep,omitempty"`
	HourUtc       int32                  `protobuf:"varint,3,opt,name=hour_utc,json=hourUtc,proto3" json:"hour_utc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseBackupPlan) Reset() {
	*x = DatabaseBackupPlan{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseBackupPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseBackupPlan) ProtoMessage() {}

func (x *DatabaseBackupPlan) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseBackupPlan.ProtoReflect.Descriptor instead.
func (*DatabaseBackupPlan) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{17}
}

func (x *DatabaseBackupPlan) GetIntervalHours() int32 {
	if x != nil {
		return x.IntervalHours
	}
	return 0
}

func (x *DatabaseBackupPlan) GetKeep() int32 {
	if x != nil {
		return x.Keep
	}
	return 0
}

func (x *DatabaseBackupPlan) GetHourUtc() int32 {
	if x != nil {
		return x.HourUtc
	}
	return 0
}

// RotateDatabaseCredentialsRequest 是凭据轮换受理（破坏性两段式：confirm =
// 实例名原样回传，mismatch → 400——与 DeleteDatabase 同型的数据安全面）。
type RotateDatabaseCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Confirm       string                 `protobuf:"bytes,2,opt,name=confirm,proto3" json:"confirm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateDatabaseCredentialsRequest) Reset() {
	*x = RotateDatabaseCredentialsRequest{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateDatabaseCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateDatabaseCredentialsRequest) ProtoMessage() {}

func (x *RotateDatabaseCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateDatabaseCredentialsRequest.ProtoReflect.Descriptor instead.
func (*RotateDatabaseCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{18}
}

func (x *RotateDatabaseCredentialsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RotateDatabaseCredentialsRequest) GetConfirm() string {
	if x != nil {
		return x.Confirm
	}
	return ""
}

type RotateDatabaseCredentialsResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Database *DatabaseView          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// 平台自动重部署的引用 app 名单（各自走正常部署队列；credential_updated_at
	// 展示随 database.credential_updated_at 刷新）。
	RedeployedApps []string `protobuf:"bytes,2,rep,name=redeployed_apps,json=redeployedApps,proto3" json:"redeployed_apps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RotateDatabaseCredentialsResponse) Reset() {
	*x = RotateDatabaseCredentialsResponse{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateDatabaseCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateDatabaseCredentialsResponse) ProtoMessage() {}

func (x *RotateDatabaseCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateDatabaseCredentialsResponse.ProtoReflect.Descriptor instead.
func (*RotateDatabaseCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{19}
}

func (x *RotateDatabaseCredentialsResponse) GetDatabase() *DatabaseView {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *RotateDatabaseCredentialsResponse) GetRedeployedApps() []string {
	if x != nil {
		return x.RedeployedApps
	}
	return nil
}

type RevealDatabaseCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealDatabaseCredentialsRequest) Reset() {
	*x = RevealDatabaseCredentialsRequest{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealDatabaseCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealDatabaseCredentialsRequest) ProtoMessage() {}

func (x *RevealDatabaseCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealDatabaseCredentialsRequest.ProtoReflect.Descriptor instead.
func (*RevealDatabaseCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{20}
}

func (x *RevealDatabaseCredentialsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// RevealDatabaseCredentialsResponse 是连接信息的显式展开投影（§2.5 键集
// 全量 + 密码明文——admin scope 专用面；值只出现在本响应，不进日志/事件/
// 审计，审计 db.reveal 只记访问事实）。
type RevealDatabaseCredentialsResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Template string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Host     string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port     int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// PG 有 user/database；Redis 不输出（空串）。
	User     string `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Database string `protobuf:"bytes,6,opt,name=database,proto3" json:"database,omitempty"`
	// 密码明文（显式展开面的设计内例外；凭据字符集 [a-zA-Z0-9]）。
	Password string `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	// 标准 URI（密码段为明文——与 GetEnv 明文读同级的 admin 面）。
	Url           string `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealDatabaseCredentialsResponse) Reset() {
	*x = RevealDatabaseCredentialsResponse{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealDatabaseCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealDatabaseCredentialsResponse) ProtoMessage() {}

func (x *RevealDatabaseCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealDatabaseCredentialsResponse.ProtoReflect.Descriptor instead.
func (*RevealDatabaseCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{21}
}

func (x *RevealDatabaseCredentialsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RevealDatabaseCredentialsResponse) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *RevealDatabaseCredentialsResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RevealDatabaseCredentialsResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RevealDatabaseCredentialsResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RevealDatabaseCredentialsResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *RevealDatabaseCredentialsResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RevealDatabaseCredentialsResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// DatabaseView 是库实例投影（状态 = 生命周期态；连接信息脱敏——密码明文
// 零离开存储，url 已掩码、password_fingerprint 供「是不是那个 secret」比
// 对；显式 reveal 面随 S4/S6）。last_error 是最近一次收敛失败原因（failed
// 诊断面；” = 无失败现场）。
type DatabaseView struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Template    string                 `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	ImageDigest string                 `protobuf:"bytes,4,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	// 生命周期状态位（provisioning|ready|failed|degraded|paused|deleting|deleted）。
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// 放置绑定（平台节点 ID；空 = 未绑定——provisioning 首拍前）。
	Placement string `protobuf:"bytes,6,opt,name=placement,proto3" json:"placement,omitempty"`
	// 数据卷投影（name = docker 卷名；status = active|orphaned|discarded；
	// 空 = 尚未登记）。
	Volume *DatabaseVolumeView `protobuf:"bytes,7,opt,name=volume,proto3" json:"volume,omitempty"`
	// 连接信息脱敏投影。
	Connection          *DatabaseConnectionView `protobuf:"bytes,8,opt,name=connection,proto3" json:"connection,omitempty"`
	BackupPlan          *DatabaseBackupPlan     `protobuf:"bytes,9,opt,name=backup_plan,json=backupPlan,proto3" json:"backup_plan,omitempty"`
	Limits              *DatabaseLimits         `protobuf:"bytes,10,opt,name=limits,proto3" json:"limits,omitempty"`
	CreatedAt           *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp  `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CredentialUpdatedAt *timestamppb.Timestamp  `protobuf:"bytes,13,opt,name=credential_updated_at,json=credentialUpdatedAt,proto3" json:"credential_updated_at,omitempty"`
	// 最近一次收敛失败原因（failed/deleting 前的现场快照；空 = 无失败现场）。
	LastError     string `protobuf:"bytes,14,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseView) Reset() {
	*x = DatabaseView{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseView) ProtoMessage() {}

func (x *DatabaseView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseView.ProtoReflect.Descriptor instead.
func (*DatabaseView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{22}
}

func (x *DatabaseView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DatabaseView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DatabaseView) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *DatabaseView) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *DatabaseView) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DatabaseView) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

func (x *DatabaseView) GetVolume() *DatabaseVolumeView {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *DatabaseView) GetConnection() *DatabaseConnectionView {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *DatabaseView) GetBackupPlan() *DatabaseBackupPlan {
	if x != nil {
		return x.BackupPlan
	}
	return nil
}

func (x *DatabaseView) GetLimits() *DatabaseLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *DatabaseView) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DatabaseView) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DatabaseView) GetCredentialUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CredentialUpdatedAt
	}
	return nil
}

func (x *DatabaseView) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type DatabaseVolumeView struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// 数据节点（卷钉住语义——与 placement 一致）。
	PlatformNodeId string `protobuf:"bytes,3,opt,name=platform_node_id,json=platformNodeId,proto3" json:"platform_node_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DatabaseVolumeView) Reset() {
	*x = DatabaseVolumeView{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseVolumeView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseVolumeView) ProtoMessage() {}

func (x *DatabaseVolumeView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseVolumeView.ProtoReflect.Descriptor instead.
func (*DatabaseVolumeView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{23}
}

func (x *DatabaseVolumeView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DatabaseVolumeView) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DatabaseVolumeView) GetPlatformNodeId() string {
	if x != nil {
		return x.PlatformNodeId
	}
	return ""
}

// DatabaseConnectionView 是连接信息脱敏投影（§2.5 键集的只读面）。url 中
// 密码段恒为固定掩码（********）——明文零离开存储；host = 实例名 DNS 别名
// （引用方 app 内即以此可达）。
type DatabaseConnectionView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Host  string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port  int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// PG 有 user/database；Redis 不输出（0 值 + 空串在 EmitUnpopulated=false
	// 下不出现）。
	User     string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Database string `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	// 掩码 URL（postgres://fleetly:********@<host>:5432/<db> / redis://:********@<host>:6379/0）。
	Url string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	// 密码指纹（sha256 前 8 hex——只判「是不是那个值」，材料零出现）。
	PasswordFingerprint string `protobuf:"bytes,6,opt,name=password_fingerprint,json=passwordFingerprint,proto3" json:"password_fingerprint,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DatabaseConnectionView) Reset() {
	*x = DatabaseConnectionView{}
	mi := &file_fleetly_server_v1_database_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseConnectionView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseConnectionView) ProtoMessage() {}

func (x *DatabaseConnectionView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_database_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseConnectionView.ProtoReflect.Descriptor instead.
func (*DatabaseConnectionView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_database_proto_rawDescGZIP(), []int{24}
}

func (x *DatabaseConnectionView) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DatabaseConnectionView) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DatabaseConnectionView) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DatabaseConnectionView) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DatabaseConnectionView) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DatabaseConnectionView) GetPasswordFingerprint() string {
	if x != nil {
		return x.PasswordFingerprint
	}
	return ""
}

var File_fleetly_server_v1_database_proto protoreflect.FileDescriptor

const file_fleetly_server_v1_database_proto_rawDesc = "" +
	"\n" +
	" fleetly/server/v1/database.proto\x12\x11fleetly.server.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xf1\x01\n" +
	"\x15CreateDatabaseRequest\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\xbaH\x19r\x172\x15^[a-z0-9][a-z0-9_-]*$R\x04name\x12#\n" +
	"\btemplate\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\btemplate\x129\n" +
	"\x06limits\x18\x03 \x01(\v2!.fleetly.server.v1.DatabaseLimitsR\x06limits\x12F\n" +
	"\vbackup_plan\x18\x04 \x01(\v2%.fleetly.server.v1.DatabaseBackupPlanR\n" +
	"backupPlan\"U\n" +
	"\x16CreateDatabaseResponse\x12;\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1f.fleetly.server.v1.DatabaseViewR\bdatabase\"1\n" +
	"\x12GetDatabaseRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"R\n" +
	"\x13GetDatabaseResponse\x12;\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1f.fleetly.server.v1.DatabaseViewR\bdatabase\"8\n" +
	"\x14ListDatabasesRequest\x12 \n" +
	"\x05limit\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00R\x05limit\"V\n" +
	"\x15ListDatabasesResponse\x12=\n" +
	"\tdatabases\x18\x01 \x03(\v2\x1f.fleetly.server.v1.DatabaseViewR\tdatabases\"u\n" +
	"\x15DeleteDatabaseRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12\x18\n" +
	"\aconfirm\x18\x02 \x01(\tR\aconfirm\x12%\n" +
	"\x0edelete_volumes\x18\x03 \x01(\bR\rdeleteVolumes\"D\n" +
	"\x16DeleteDatabaseResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"5\n" +
	"\x16SuspendDatabaseRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"V\n" +
	"\x17SuspendDatabaseResponse\x12;\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1f.fleetly.server.v1.DatabaseViewR\bdatabase\"4\n" +
	"\x15ResumeDatabaseRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"U\n" +
	"\x16ResumeDatabaseResponse\x12;\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1f.fleetly.server.v1.DatabaseViewR\bdatabase\"3\n" +
	"\x14RetryDatabaseRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"T\n" +
	"\x15RetryDatabaseResponse\x12;\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1f.fleetly.server.v1.DatabaseViewR\bdatabase\"\xbf\x01\n" +
	"\x1dUpdateDatabaseSettingsRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x129\n" +
	"\x06limits\x18\x02 \x01(\v2!.fleetly.server.v1.DatabaseLimitsR\x06limits\x12F\n" +
	"\vbackup_plan\x18\x03 \x01(\v2%.fleetly.server.v1.DatabaseBackupPlanR\n" +
	"backupPlan\"]\n" +
	"\x1eUpdateDatabaseSettingsResponse\x12;\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1f.fleetly.server.v1.DatabaseViewR\bdatabase\"T\n" +
	"\x0eDatabaseLimits\x12\x1f\n" +
	"\vcpu_seconds\x18\x01 \x01(\x01R\n" +
	"cpuSeconds\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\"j\n" +
	"\x12DatabaseBackupPlan\x12%\n" +
	"\x0einterval_hours\x18\x01 \x01(\x05R\rintervalHours\x12\x12\n" +
	"\x04keep\x18\x02 \x01(\x05R\x04keep\x12\x19\n" +
	"\bhour_utc\x18\x03 \x01(\x05R\ahourUtc\"Y\n" +
	" RotateDatabaseCredentialsRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12\x18\n" +
	"\aconfirm\x18\x02 \x01(\tR\aconfirm\"\x89\x01\n" +
	"!RotateDatabaseCredentialsResponse\x12;\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1f.fleetly.server.v1.DatabaseViewR\bdatabase\x12'\n" +
	"\x0fredeployed_apps\x18\x02 \x03(\tR\x0eredeployedApps\"?\n" +
	" RevealDatabaseCredentialsRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"\xd9\x01\n" +
	"!RevealDatabaseCredentialsResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12\x1a\n" +
	"\bdatabase\x18\x06 \x01(\tR\bdatabase\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\"\x99\x05\n" +
	"\fDatabaseView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\btemplate\x18\x03 \x01(\tR\btemplate\x12!\n" +
	"\fimage_digest\x18\x04 \x01(\tR\vimageDigest\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1c\n" +
	"\tplacement\x18\x06 \x01(\tR\tplacement\x12=\n" +
	"\x06volume\x18\a \x01(\v2%.fleetly.server.v1.DatabaseVolumeViewR\x06volume\x12I\n" +
	"\n" +
	"connection\x18\b \x01(\v2).fleetly.server.v1.DatabaseConnectionViewR\n" +
	"connection\x12F\n" +
	"\vbackup_plan\x18\t \x01(\v2%.fleetly.server.v1.DatabaseBackupPlanR\n" +
	"backupPlan\x129\n" +
	"\x06limits\x18\n" +
	" \x01(\v2!.fleetly.server.v1.DatabaseLimitsR\x06limits\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12N\n" +
	"\x15credential_updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x13credentialUpdatedAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\x0e \x01(\tR\tlastError\"j\n" +
	"\x12DatabaseVolumeView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12(\n" +
	"\x10platform_node_id\x18\x03 \x01(\tR\x0eplatformNodeId\"\xb5\x01\n" +
	"\x16DatabaseConnectionView\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x121\n" +
	"\x14password_fingerprint\x18\x06 \x01(\tR\x13passwordFingerprint2\xcd\v\n" +
	"\x0fDatabaseService\x12\x7f\n" +
	"\x0eCreateDatabase\x12(.fleetly.server.v1.CreateDatabaseRequest\x1a).fleetly.server.v1.CreateDatabaseResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/databases\x12z\n" +
	"\vGetDatabase\x12%.fleetly.server.v1.GetDatabaseRequest\x1a&.fleetly.server.v1.GetDatabaseResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/databases/{name}\x12y\n" +
	"\rListDatabases\x12'.fleetly.server.v1.ListDatabasesRequest\x1a(.fleetly.server.v1.ListDatabasesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/databases\x12\x83\x01\n" +
	"\x0eDeleteDatabase\x12(.fleetly.server.v1.DeleteDatabaseRequest\x1a).fleetly.server.v1.DeleteDatabaseResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/databases/{name}\x12\x91\x01\n" +
	"\x0fSuspendDatabase\x12).fleetly.server.v1.SuspendDatabaseRequest\x1a*.fleetly.server.v1.SuspendDatabaseResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/databases/{name}/suspend\x12\x8d\x01\n" +
	"\x0eResumeDatabase\x12(.fleetly.server.v1.ResumeDatabaseRequest\x1a).fleetly.server.v1.ResumeDatabaseResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/databases/{name}/resume\x12\x89\x01\n" +
	"\rRetryDatabase\x12'.fleetly.server.v1.RetryDatabaseRequest\x1a(.fleetly.server.v1.RetryDatabaseResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/databases/{name}/retry\x12\xa7\x01\n" +
	"\x16UpdateDatabaseSettings\x120.fleetly.server.v1.UpdateDatabaseSettingsRequest\x1a1.fleetly.server.v1.UpdateDatabaseSettingsResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\x1a\x1d/v1/databases/{name}/settings\x12\xae\x01\n" +
	"\x19RotateDatabaseCredentials\x123.fleetly.server.v1.RotateDatabaseCredentialsRequest\x1a4.fleetly.server.v1.RotateDatabaseCredentialsResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/databases/{name}/rotate\x12\xb0\x01\n" +
	"\x19RevealDatabaseCredentials\x123.fleetly.server.v1.RevealDatabaseCredentialsRequest\x1a4.fleetly.server.v1.RevealDatabaseCredentialsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/databases/{name}/credentialsB\x98\x01\x92ARRP\n" +
	"\adefault\x12E\n" +
	"\x1dAn unexpected error response.\x12$\n" +
	"\"\x1a .fleetly.shared.v1.ErrorResponseZAgithub.com/fleetlyrun/fleetly/genproto/fleetly/server/v1;serverv1b\x06proto3"

var (
	file_fleetly_server_v1_database_proto_rawDescOnce sync.Once
	file_fleetly_server_v1_database_proto_rawDescData []byte
)

func file_fleetly_server_v1_database_proto_rawDescGZIP() []byte {
	file_fleetly_server_v1_database_proto_rawDescOnce.Do(func() {
		file_fleetly_server_v1_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_database_proto_rawDesc), len(file_fleetly_server_v1_database_proto_rawDesc)))
	})
	return file_fleetly_server_v1_database_proto_rawDescData
}

var file_fleetly_server_v1_database_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_fleetly_server_v1_database_proto_goTypes = []any{
	(*CreateDatabaseRequest)(nil),             // 0: fleetly.server.v1.CreateDatabaseRequest
	(*CreateDatabaseResponse)(nil),            // 1: fleetly.server.v1.CreateDatabaseResponse
	(*GetDatabaseRequest)(nil),                // 2: fleetly.server.v1.GetDatabaseRequest
	(*GetDatabaseResponse)(nil),               // 3: fleetly.server.v1.GetDatabaseResponse
	(*ListDatabasesRequest)(nil),              // 4: fleetly.server.v1.ListDatabasesRequest
	(*ListDatabasesResponse)(nil),             // 5: fleetly.server.v1.ListDatabasesResponse
	(*DeleteDatabaseRequest)(nil),             // 6: fleetly.server.v1.DeleteDatabaseRequest
	(*DeleteDatabaseResponse)(nil),            // 7: fleetly.server.v1.DeleteDatabaseResponse
	(*SuspendDatabaseRequest)(nil),            // 8: fleetly.server.v1.SuspendDatabaseRequest
	(*SuspendDatabaseResponse)(nil),           // 9: fleetly.server.v1.SuspendDatabaseResponse
	(*ResumeDatabaseRequest)(nil),             // 10: fleetly.server.v1.ResumeDatabaseRequest
	(*ResumeDatabaseResponse)(nil),            // 11: fleetly.server.v1.ResumeDatabaseResponse
	(*RetryDatabaseRequest)(nil),              // 12: fleetly.server.v1.RetryDatabaseRequest
	(*RetryDatabaseResponse)(nil),             // 13: fleetly.server.v1.RetryDatabaseResponse
	(*UpdateDatabaseSettingsRequest)(nil),     // 14: fleetly.server.v1.UpdateDatabaseSettingsRequest
	(*UpdateDatabaseSettingsResponse)(nil),    // 15: fleetly.server.v1.UpdateDatabaseSettingsResponse
	(*DatabaseLimits)(nil),                    // 16: fleetly.server.v1.DatabaseLimits
	(*DatabaseBackupPlan)(nil),                // 17: fleetly.server.v1.DatabaseBackupPlan
	(*RotateDatabaseCredentialsRequest)(nil),  // 18: fleetly.server.v1.RotateDatabaseCredentialsRequest
	(*RotateDatabaseCredentialsResponse)(nil), // 19: fleetly.server.v1.RotateDatabaseCredentialsResponse
	(*RevealDatabaseCredentialsRequest)(nil),  // 20: fleetly.server.v1.RevealDatabaseCredentialsRequest
	(*RevealDatabaseCredentialsResponse)(nil), // 21: fleetly.server.v1.RevealDatabaseCredentialsResponse
	(*DatabaseView)(nil),                      // 22: fleetly.server.v1.DatabaseView
	(*DatabaseVolumeView)(nil),                // 23: fleetly.server.v1.DatabaseVolumeView
	(*DatabaseConnectionView)(nil),            // 24: fleetly.server.v1.DatabaseConnectionView
	(*timestamppb.Timestamp)(nil),             // 25: google.protobuf.Timestamp
}
var file_fleetly_server_v1_database_proto_depIdxs = []int32{
	16, // 0: fleetly.server.v1.CreateDatabaseRequest.limits:type_name -> fleetly.server.v1.DatabaseLimits
	17, // 1: fleetly.server.v1.CreateDatabaseRequest.backup_plan:type_name -> fleetly.server.v1.DatabaseBackupPlan
	22, // 2: fleetly.server.v1.CreateDatabaseResponse.database:type_name -> fleetly.server.v1.DatabaseView
	22, // 3: fleetly.server.v1.GetDatabaseResponse.database:type_name -> fleetly.server.v1.DatabaseView
	22, // 4: fleetly.server.v1.ListDatabasesResponse.databases:type_name -> fleetly.server.v1.DatabaseView
	22, // 5: fleetly.server.v1.SuspendDatabaseResponse.database:type_name -> fleetly.server.v1.DatabaseView
	22, // 6: fleetly.server.v1.ResumeDatabaseResponse.database:type_name -> fleetly.server.v1.DatabaseView
	22, // 7: fleetly.server.v1.RetryDatabaseResponse.database:type_name -> fleetly.server.v1.DatabaseView
	16, // 8: fleetly.server.v1.UpdateDatabaseSettingsRequest.limits:type_name -> fleetly.server.v1.DatabaseLimits
	17, // 9: fleetly.server.v1.UpdateDatabaseSettingsRequest.backup_plan:type_name -> fleetly.server.v1.DatabaseBackupPlan
	22, // 10: fleetly.server.v1.UpdateDatabaseSettingsResponse.database:type_name -> fleetly.server.v1.DatabaseView
	22, // 11: fleetly.server.v1.RotateDatabaseCredentialsResponse.database:type_name -> fleetly.server.v1.DatabaseView
	23, // 12: fleetly.server.v1.DatabaseView.volume:type_name -> fleetly.server.v1.DatabaseVolumeView
	24, // 13: fleetly.server.v1.DatabaseView.connection:type_name -> fleetly.server.v1.DatabaseConnectionView
	17, // 14: fleetly.server.v1.DatabaseView.backup_plan:type_name -> fleetly.server.v1.DatabaseBackupPlan
	16, // 15: fleetly.server.v1.DatabaseView.limits:type_name -> fleetly.server.v1.DatabaseLimits
	25, // 16: fleetly.server.v1.DatabaseView.created_at:type_name -> google.protobuf.Timestamp
	25, // 17: fleetly.server.v1.DatabaseView.updated_at:type_name -> google.protobuf.Timestamp
	25, // 18: fleetly.server.v1.DatabaseView.credential_updated_at:type_name -> google.protobuf.Timestamp
	0,  // 19: fleetly.server.v1.DatabaseService.CreateDatabase:input_type -> fleetly.server.v1.CreateDatabaseRequest
	2,  // 20: fleetly.server.v1.DatabaseService.GetDatabase:input_type -> fleetly.server.v1.GetDatabaseRequest
	4,  // 21: fleetly.server.v1.DatabaseService.ListDatabases:input_type -> fleetly.server.v1.ListDatabasesRequest
	6,  // 22: fleetly.server.v1.DatabaseService.DeleteDatabase:input_type -> fleetly.server.v1.DeleteDatabaseRequest
	8,  // 23: fleetly.server.v1.DatabaseService.SuspendDatabase:input_type -> fleetly.server.v1.SuspendDatabaseRequest
	10, // 24: fleetly.server.v1.DatabaseService.ResumeDatabase:input_type -> fleetly.server.v1.ResumeDatabaseRequest
	12, // 25: fleetly.server.v1.DatabaseService.RetryDatabase:input_type -> fleetly.server.v1.RetryDatabaseRequest
	14, // 26: fleetly.server.v1.DatabaseService.UpdateDatabaseSettings:input_type -> fleetly.server.v1.UpdateDatabaseSettingsRequest
	18, // 27: fleetly.server.v1.DatabaseService.RotateDatabaseCredentials:input_type -> fleetly.server.v1.RotateDatabaseCredentialsRequest
	20, // 28: fleetly.server.v1.DatabaseService.RevealDatabaseCredentials:input_type -> fleetly.server.v1.RevealDatabaseCredentialsRequest
	1,  // 29: fleetly.server.v1.DatabaseService.CreateDatabase:output_type -> fleetly.server.v1.CreateDatabaseResponse
	3,  // 30: fleetly.server.v1.DatabaseService.GetDatabase:output_type -> fleetly.server.v1.GetDatabaseResponse
	5,  // 31: fleetly.server.v1.DatabaseService.ListDatabases:output_type -> fleetly.server.v1.ListDatabasesResponse
	7,  // 32: fleetly.server.v1.DatabaseService.DeleteDatabase:output_type -> fleetly.server.v1.DeleteDatabaseResponse
	9,  // 33: fleetly.server.v1.DatabaseService.SuspendDatabase:output_type -> fleetly.server.v1.SuspendDatabaseResponse
	11, // 34: fleetly.server.v1.DatabaseService.ResumeDatabase:output_type -> fleetly.server.v1.ResumeDatabaseResponse
	13, // 35: fleetly.server.v1.DatabaseService.RetryDatabase:output_type -> fleetly.server.v1.RetryDatabaseResponse
	15, // 36: fleetly.server.v1.DatabaseService.UpdateDatabaseSettings:output_type -> fleetly.server.v1.UpdateDatabaseSettingsResponse
	19, // 37: fleetly.server.v1.DatabaseService.RotateDatabaseCredentials:output_type -> fleetly.server.v1.RotateDatabaseCredentialsResponse
	21, // 38: fleetly.server.v1.DatabaseService.RevealDatabaseCredentials:output_type -> fleetly.server.v1.RevealDatabaseCredentialsResponse
	29, // [29:39] is the sub-list for method output_type
	19, // [19:29] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_fleetly_server_v1_database_proto_init() }
func file_fleetly_server_v1_database_proto_init() {
	if File_fleetly_server_v1_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_database_proto_rawDesc), len(file_fleetly_server_v1_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetly_server_v1_database_proto_goTypes,
		DependencyIndexes: file_fleetly_server_v1_database_proto_depIdxs,
		MessageInfos:      file_fleetly_server_v1_database_proto_msgTypes,
	}.Build()
	File_fleetly_server_v1_database_proto = out.File
	file_fleetly_server_v1_database_proto_goTypes = nil
	file_fleetly_server_v1_database_proto_depIdxs = nil
}
