// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fleetly/server/v1/logs.proto

package serverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	App   string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// compose 服务名；空 = 该 app 全部服务。
	Service       string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowLogsRequest) Reset() {
	*x = FollowLogsRequest{}
	mi := &file_fleetly_server_v1_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowLogsRequest) ProtoMessage() {}

func (x *FollowLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowLogsRequest.ProtoReflect.Descriptor instead.
func (*FollowLogsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_logs_proto_rawDescGZIP(), []int{0}
}

func (x *FollowLogsRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *FollowLogsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type ListHistoryLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	App   string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// compose 服务名；空 = 全部服务。
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// 时间窗下界；缺省 = 保留窗起点。
	Since *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	// 时间窗上界；缺省 = 现在。
	Until *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=until,proto3" json:"until,omitempty"`
	// 返回上限（缺省 200，天花板 1000；超过取最新 limit 条）。
	Limit int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// 来源过滤：container | build；空 = 全部。
	Source        string `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoryLogsRequest) Reset() {
	*x = ListHistoryLogsRequest{}
	mi := &file_fleetly_server_v1_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryLogsRequest) ProtoMessage() {}

func (x *ListHistoryLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryLogsRequest.ProtoReflect.Descriptor instead.
func (*ListHistoryLogsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_logs_proto_rawDescGZIP(), []int{1}
}

func (x *ListHistoryLogsRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ListHistoryLogsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ListHistoryLogsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListHistoryLogsRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *ListHistoryLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListHistoryLogsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// LogEntryView 是单条日志投影。source ∈ container | build。
type LogEntryView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	Stderr        bool                   `protobuf:"varint,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Line          string                 `protobuf:"bytes,5,opt,name=line,proto3" json:"line,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntryView) Reset() {
	*x = LogEntryView{}
	mi := &file_fleetly_server_v1_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryView) ProtoMessage() {}

func (x *LogEntryView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryView.ProtoReflect.Descriptor instead.
func (*LogEntryView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_logs_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntryView) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *LogEntryView) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogEntryView) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *LogEntryView) GetStderr() bool {
	if x != nil {
		return x.Stderr
	}
	return false
}

func (x *LogEntryView) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogEntryView) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type FollowLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *LogEntryView          `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowLogsResponse) Reset() {
	*x = FollowLogsResponse{}
	mi := &file_fleetly_server_v1_logs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowLogsResponse) ProtoMessage() {}

func (x *FollowLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_logs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowLogsResponse.ProtoReflect.Descriptor instead.
func (*FollowLogsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_logs_proto_rawDescGZIP(), []int{3}
}

func (x *FollowLogsResponse) GetEntry() *LogEntryView {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ListHistoryLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntryView        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoryLogsResponse) Reset() {
	*x = ListHistoryLogsResponse{}
	mi := &file_fleetly_server_v1_logs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryLogsResponse) ProtoMessage() {}

func (x *ListHistoryLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_logs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryLogsResponse.ProtoReflect.Descriptor instead.
func (*ListHistoryLogsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_logs_proto_rawDescGZIP(), []int{4}
}

func (x *ListHistoryLogsResponse) GetEntries() []*LogEntryView {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_fleetly_server_v1_logs_proto protoreflect.FileDescriptor

const file_fleetly_server_v1_logs_proto_rawDesc = "" +
	"\n" +
	"\x1cfleetly/server/v1/logs.proto\x12\x11fleetly.server.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"H\n" +
	"\x11FollowLogsRequest\x12\x19\n" +
	"\x03app\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03app\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"\x86\x02\n" +
	"\x16ListHistoryLogsRequest\x12\x19\n" +
	"\x03app\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03app\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\x12 \n" +
	"\x05limit\x18\x05 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00R\x05limit\x121\n" +
	"\x06source\x18\x06 \x01(\tB\x19\xbaH\x16r\x14R\x00R\tcontainerR\x05buildR\x06source\"\xaa\x01\n" +
	"\fLogEntryView\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\bR\x06stderr\x12\x12\n" +
	"\x04line\x18\x05 \x01(\tR\x04line\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\"K\n" +
	"\x12FollowLogsResponse\x125\n" +
	"\x05entry\x18\x01 \x01(\v2\x1f.fleetly.server.v1.LogEntryViewR\x05entry\"T\n" +
	"\x17ListHistoryLogsResponse\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.fleetly.server.v1.LogEntryViewR\aentries2\x96\x02\n" +
	"\vLogsService\x12\x7f\n" +
	"\n" +
	"FollowLogs\x12$.fleetly.server.v1.FollowLogsRequest\x1a%.fleetly.server.v1.FollowLogsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/apps/{app}/logs/stream0\x01\x12\x85\x01\n" +
	"\x0fListHistoryLogs\x12).fleetly.server.v1.ListHistoryLogsRequest\x1a*.fleetly.server.v1.ListHistoryLogsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/apps/{app}/logsB\x98\x01\x92ARRP\n" +
	"\adefault\x12E\n" +
	"\x1dAn unexpected error response.\x12$\n" +
	"\"\x1a .fleetly.shared.v1.ErrorResponseZAgithub.com/fleetlyrun/fleetly/genproto/fleetly/server/v1;serverv1b\x06proto3"

var (
	file_fleetly_server_v1_logs_proto_rawDescOnce sync.Once
	file_fleetly_server_v1_logs_proto_rawDescData []byte
)

func file_fleetly_server_v1_logs_proto_rawDescGZIP() []byte {
	file_fleetly_server_v1_logs_proto_rawDescOnce.Do(func() {
		file_fleetly_server_v1_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_logs_proto_rawDesc), len(file_fleetly_server_v1_logs_proto_rawDesc)))
	})
	return file_fleetly_server_v1_logs_proto_rawDescData
}

var file_fleetly_server_v1_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fleetly_server_v1_logs_proto_goTypes = []any{
	(*FollowLogsRequest)(nil),       // 0: fleetly.server.v1.FollowLogsRequest
	(*ListHistoryLogsRequest)(nil),  // 1: fleetly.server.v1.ListHistoryLogsRequest
	(*LogEntryView)(nil),            // 2: fleetly.server.v1.LogEntryView
	(*FollowLogsResponse)(nil),      // 3: fleetly.server.v1.FollowLogsResponse
	(*ListHistoryLogsResponse)(nil), // 4: fleetly.server.v1.ListHistoryLogsResponse
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_fleetly_server_v1_logs_proto_depIdxs = []int32{
	5, // 0: fleetly.server.v1.ListHistoryLogsRequest.since:type_name -> google.protobuf.Timestamp
	5, // 1: fleetly.server.v1.ListHistoryLogsRequest.until:type_name -> google.protobuf.Timestamp
	5, // 2: fleetly.server.v1.LogEntryView.at:type_name -> google.protobuf.Timestamp
	2, // 3: fleetly.server.v1.FollowLogsResponse.entry:type_name -> fleetly.server.v1.LogEntryView
	2, // 4: fleetly.server.v1.ListHistoryLogsResponse.entries:type_name -> fleetly.server.v1.LogEntryView
	0, // 5: fleetly.server.v1.LogsService.FollowLogs:input_type -> fleetly.server.v1.FollowLogsRequest
	1, // 6: fleetly.server.v1.LogsService.ListHistoryLogs:input_type -> fleetly.server.v1.ListHistoryLogsRequest
	3, // 7: fleetly.server.v1.LogsService.FollowLogs:output_type -> fleetly.server.v1.FollowLogsResponse
	4, // 8: fleetly.server.v1.LogsService.ListHistoryLogs:output_type -> fleetly.server.v1.ListHistoryLogsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_fleetly_server_v1_logs_proto_init() }
func file_fleetly_server_v1_logs_proto_init() {
	if File_fleetly_server_v1_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_logs_proto_rawDesc), len(file_fleetly_server_v1_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetly_server_v1_logs_proto_goTypes,
		DependencyIndexes: file_fleetly_server_v1_logs_proto_depIdxs,
		MessageInfos:      file_fleetly_server_v1_logs_proto_msgTypes,
	}.Build()
	File_fleetly_server_v1_logs_proto = out.File
	file_fleetly_server_v1_logs_proto_goTypes = nil
	file_fleetly_server_v1_logs_proto_depIdxs = nil
}
