/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/apps/{app_id}/hook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HooksService_GetGitHook"];
        put?: never;
        /**
         * SetGitHook 建/改配置；无 Token 时铸造（明文只在本响应出现一次，
         *     同一串兼作 GitHub webhook secret）。已配置过再 Set 只改配置不换 Token
         *     （换 Token 用 RotateHookToken）。
         */
        post: operations["HooksService_SetGitHook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/apps/{app_id}/hook/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * RotateHookToken 吊销旧 Token 铸新（URL token 与 GitHub webhook secret
         *     同源双换；旧 Token 即刻失效）。
         */
        post: operations["HooksService_RotateHookToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/apps/{app_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollback 是一等动词（F0.11）：Revision Replay——空目标回上一成功基线。 */
        post: operations["DeploymentsService_Rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BuildsService_ListBuilds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/builds/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * StreamBuildLogs 读构建日志（B4：消费引擎最近缓冲——诚实边界同 F0.25
         *     "仅实时+最近缓冲"，持久化检索 N2；follow 随构建推进续流至终态）。
         */
        get: operations["BuildsService_StreamBuildLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/builds/{build_id}/wait": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** WaitBuild 是构建等待原语（F1.3，架构 §7）：状态快照帧，终态帧后收流。 */
        get: operations["BuildsService_WaitBuild"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DeploymentsService_ListDeployments"];
        put?: never;
        /** Deploy 归一化两源（镜像直投 / Compose 受控子集）并受理部署。 */
        post: operations["DeploymentsService_Deploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_id}/wait": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WaitDeployment 是等待原语（F1.3，架构 §7）：事件流过滤实现——逐状态
         *     快照帧，终态帧后收流。Agent/Console 的"部署-等待-验证"循环不必自写
         *     轮询。WaitRun 随 Run 实体（F1.5/6）落地，不预发空面。
         */
        get: operations["DeploymentsService_WaitDeployment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DeploymentsService_GetDeployment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeploymentsService_CancelDeployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RevisionsService_ListRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/revisions/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** DiffRevisions 输出两条 Revision 的字段级差异（路径字典序）。 */
        get: operations["RevisionsService_DiffRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListUploads 列项目上传产物（after_upload_id + limit 游标，ADR-0026
         *     List 惯例）。
         */
        get: operations["BuildsService_ListUploads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DeploymentsServiceCancelDeploymentBody: Record<string, never>;
        DeploymentsServiceRollbackBody: {
            to_revision?: string;
        };
        HooksServiceRotateHookTokenBody: Record<string, never>;
        HooksServiceSetGitHookBody: {
            repo?: string;
            branch?: string;
            dockerfile?: string;
            watch_paths?: string[];
        };
        /**
         * Admission 是创建型部署受理的判定附注（P10：ADR-0016 语义的响应面显式
         *     化——调用方（尤其 Agent）可判定"去重命中/排队第几位"，UI/API/webhook
         *     三入口一致）。
         */
        v1Admission: {
            /**
             * outcome 四形态：queued（新受理，无合并无抢占）| merged（latest-wins：
             *     既有 queued 请求被本请求合并取代）| superseded（显式 supersede 抢占
             *     在途部署；同批合并的 queued 不另报）| deduplicated（同幂等键或同
             *     commit 命中活跃既有部署）。幂等层命中（ADR-0024）逐字节重放原始
             *     响应、不标 deduplicated——幂等层与 admission 去重在响应里天然分立。
             */
            outcome?: string;
            /**
             * position 是本部署在 per-App 串行管线中的位次（1 = 队头/下一执行）；
             *     在途部署在前计位，被合并/被抢占的不计。deduplicated 时是命中既有
             *     部署的位次。
             * Format: int32
             */
            position?: number;
            /**
             * existing_deployment 在 outcome=deduplicated 时携带命中的既有部署引用
             *     （与 deployment 字段同值——单独携带供程序化消费，不必比对）。
             */
            existing_deployment?: string;
        };
        v1Build: {
            id?: string;
            app_id?: string;
            revision_id?: string;
            state?: string;
            digest?: string;
            error?: string;
            created_at?: string;
            finished_at?: string;
        };
        v1CancelDeploymentResponse: {
            deployment?: components["schemas"]["v1Deployment"];
        };
        /** DeployRequest 三源（互斥；spec_file 已归一化 AppSpec JSON 随 API 扩展批）。 */
        v1DeployRequest: {
            app_id?: string;
            /** image 直投形态（如 nginx:1.27）。 */
            image?: string;
            /** compose_yaml 受控子集形态（白名单执法、受管字段显式拒绝）。 */
            compose_yaml?: string;
            idempotency_key?: string;
            commit_sha?: string;
            supersede?: boolean;
            /** process_name 覆盖直投/上传形态的进程名（默认 web）。 */
            process_name?: string;
            /**
             * http_probe/tcp_probe 是直投与上传形态的探针声明（B2：http/tcp 探针的
             *     API 声明面，互斥；compose 形态经 healthcheck.http_path/tcp_port 扩展键）。
             */
            http_probe?: string;
            /** Format: int32 */
            tcp_probe?: number;
            /**
             * upload_id 是上传产物形态（F1.10，ADR-0019 附录 A）：引用 UploadSource
             *     返回的 id，与 image/compose_yaml 互斥；归属项目必须与 App 一致。
             */
            upload_id?: string;
            /** dockerfile 是上传形态的构建文件路径（tar 内相对路径，缺省 Dockerfile）。 */
            dockerfile?: string;
            /**
             * builder 是上传形态的构建器选择（dockerfile|railpack|static，ADR-0032；
             *     缺省 dockerfile；image/compose 形态携带即拒）。
             */
            builder?: string;
            /**
             * railpack_version 是 railpack 形态的钉版声明（builder=railpack 必填，
             *     bare semver，须等于平台钉版）。
             */
            railpack_version?: string;
            /** output_dir 是 static 形态的产物目录（builder=static 可选，缺省 "."）。 */
            output_dir?: string;
            /**
             * env 是 App 级变量直传（ADR-0043 决策 2）：image/upload 形态的单进程
             *     环境变量；归一化期覆盖 Project 层 SharedVariable（同键）。compose 形态
             *     自带 environment 声明面，携带即拒。
             */
            env?: {
                [key: string]: string;
            };
        };
        v1DeployResponse: {
            deployment?: components["schemas"]["v1Deployment"];
            admission?: components["schemas"]["v1Admission"];
        };
        /** Deployment 是受监督迁移的行形态（状态机值 kebab-case 与存储一致）。 */
        v1Deployment: {
            id?: string;
            app_id?: string;
            from_revision?: string;
            to_revision?: string;
            state?: string;
            /** Format: uint64 */
            generation?: string;
            idempotency_key?: string;
            commit_sha?: string;
            superseded_by?: string;
            error?: string;
            observe_deadline?: string;
            created_at?: string;
            updated_at?: string;
            finished_at?: string;
            /**
             * first_boot_task_id 是部署当前锚定的 firstBootJobs 作业 Task（releasing
             *     态 jobs 子相位非空；无作业或已完成为空。ADR-0030）。
             */
            first_boot_task_id?: string;
        };
        v1DiffEntry: {
            path?: string;
            old_value?: string;
            new_value?: string;
        };
        v1DiffRevisionsResponse: {
            entries?: components["schemas"]["v1DiffEntry"][];
        };
        v1GetDeploymentResponse: {
            deployment?: components["schemas"]["v1Deployment"];
        };
        v1GetGitHookResponse: {
            hook?: components["schemas"]["v1GitHook"];
        };
        /**
         * GitHook 是 per-App Git 触发配置投影（secret 永不回显——完整明文只在
         *     铸造响应出现一次）。
         */
        v1GitHook: {
            app_id?: string;
            /** 仓库 URL（构建检出源） */
            repo?: string;
            /** 分支过滤（空 = 全部分支；tag 一律不触发） */
            branch?: string;
            /** 构建文件路径（缺省 Dockerfile） */
            dockerfile?: string;
            /** 触发路径前缀（空 = 全部变更触发） */
            watch_paths?: string[];
            /** URL token 前缀（泄露识别锚） */
            token_prefix?: string;
            created_at?: string;
            updated_at?: string;
        };
        v1ListBuildsResponse: {
            builds?: components["schemas"]["v1Build"][];
        };
        v1ListDeploymentsResponse: {
            deployments?: components["schemas"]["v1Deployment"][];
        };
        v1ListRevisionsResponse: {
            revisions?: components["schemas"]["v1Revision"][];
        };
        v1ListUploadsResponse: {
            uploads?: components["schemas"]["v1Upload"][];
        };
        v1ReceiveWebhookResponse: {
            /**
             * status: pong（ping 事件）| accepted | skipped | ignored
             *     （非 ping/push 事件）。重投不设独立状态：同 delivery 重投经幂等键
             *     重放首次响应（ADR-0024/Q-21）。
             */
            status?: string;
            /** skipped 细节（branch/path/skip 标记） */
            reason?: string;
            deployment_id?: string;
            admission?: components["schemas"]["v1Admission"];
        };
        v1Revision: {
            id?: string;
            app_id?: string;
            /** Format: int64 */
            seq?: string;
            digest?: string;
            created_at?: string;
        };
        v1RollbackResponse: {
            deployment?: components["schemas"]["v1Deployment"];
            admission?: components["schemas"]["v1Admission"];
        };
        v1RotateHookTokenResponse: {
            hook?: components["schemas"]["v1GitHook"];
            /** 新明文，仅此一次 */
            secret?: string;
        };
        v1SetGitHookResponse: {
            hook?: components["schemas"]["v1GitHook"];
            /**
             * secret 是完整明文（flthook_ 前缀），仅首次配置铸造时返回一次；同一串
             *     用作 GitHub 仓库的 webhook secret。
             */
            secret?: string;
        };
        /** StreamBuildLogsResponse 一帧构建日志（time RFC3339）。 */
        v1StreamBuildLogsResponse: {
            build_id?: string;
            time?: string;
            /** Format: byte */
            line?: string;
        };
        /** Upload 是上传产物行投影（ListUploads 读面）。 */
        v1Upload: {
            id?: string;
            project_id?: string;
            digest?: string;
            /** Format: int64 */
            size_bytes?: string;
            created_at?: string;
        };
        /**
         * UploadSourceMeta 是上传首帧：Upload 是 project 级材料（与 Secret/Config
         *     同口径——跨 App 共享，归属校验在 Deploy 受理位）。
         */
        v1UploadSourceMeta: {
            project_id?: string;
        };
        /**
         * UploadSourceResponse 是上传终态：id 是后续 Deploy 的 upload_id。同字节
         *     重传返回同一 id（deduplicated=true）。
         */
        v1UploadSourceResponse: {
            id?: string;
            /** sha256 hex（内容寻址） */
            digest?: string;
            /** Format: int64 */
            size_bytes?: string;
            deduplicated?: boolean;
        };
        /** WaitBuildResponse 是状态快照帧；流在终态帧后关闭。 */
        v1WaitBuildResponse: {
            build?: components["schemas"]["v1Build"];
        };
        /**
         * WaitDeploymentResponse 是状态快照帧；流在终态帧后关闭（终态集见
         *     Deployment.state 注释）。
         */
        v1WaitDeploymentResponse: {
            deployment?: components["schemas"]["v1Deployment"];
        };
        ErrorResponse: {
            code?: string;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HooksService_GetGitHook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1GetGitHookResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    HooksService_SetGitHook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HooksServiceSetGitHookBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1SetGitHookResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    HooksService_RotateHookToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HooksServiceRotateHookTokenBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1RotateHookTokenResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeploymentsService_Rollback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeploymentsServiceRollbackBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1RollbackResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    BuildsService_ListBuilds: {
        parameters: {
            query?: {
                app_id?: string;
                /**
                 * @description after_build_id 游标（上一页末条 id；空 = 首页）。新→旧（ULID 创建
                 *     序；ADR-0026 after_* + limit 惯例）。
                 */
                after_build_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListBuildsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    BuildsService_StreamBuildLogs: {
        parameters: {
            query?: {
                build_id?: string;
                follow?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response.(streaming responses) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: components["schemas"]["v1StreamBuildLogsResponse"];
                    };
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    BuildsService_WaitBuild: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response.(streaming responses) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: components["schemas"]["v1WaitBuildResponse"];
                    };
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeploymentsService_ListDeployments: {
        parameters: {
            query?: {
                app_id?: string;
                /**
                 * @description after_deployment_id 游标（上一页末条 id；空 = 首页）。新→旧（ULID
                 *     创建序；ADR-0026 after_* + limit 惯例）。
                 */
                after_deployment_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListDeploymentsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeploymentsService_Deploy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1DeployRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeployResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeploymentsService_WaitDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response.(streaming responses) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        result?: components["schemas"]["v1WaitDeploymentResponse"];
                    };
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeploymentsService_GetDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1GetDeploymentResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeploymentsService_CancelDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeploymentsServiceCancelDeploymentBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1CancelDeploymentResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    RevisionsService_ListRevisions: {
        parameters: {
            query?: {
                app_id?: string;
                /**
                 * @description after_seq 游标（上一页末条 seq；0 = 首页）。游标轴 = App 内 R1..Rn
                 *     单调序号升序（既有响应序不变，events 面同款升序形态；ADR-0026）。
                 */
                after_seq?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListRevisionsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    RevisionsService_DiffRevisions: {
        parameters: {
            query?: {
                app_id?: string;
                /** @description from/to 是 App 内 Revision 序号（R1..Rn 对外形态）。 */
                from_seq?: string;
                to_seq?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DiffRevisionsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    BuildsService_ListUploads: {
        parameters: {
            query?: {
                project_id?: string;
                after_upload_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListUploadsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
