// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lynx-go/lynx"
	"github.com/lynx-go/lynx/boot"
	"log/slog"
)

// Injectors from wire.go:

func wireBootstrap(app lynx.App, slogger *slog.Logger) (*boot.Bootstrap, func(), error) {
	preStartHooks := NewPreStarts(app)
	drainHooks := NewDrains()
	preStopHooks := NewPreStops(app)
	postStopHooks := NewPostStops()
	appConfig, err := NewConfig(app)
	if err != nil {
		return nil, nil, err
	}
	store, cleanup, err := NewStore(appConfig)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := NewSubstrateClient(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dockerClient, cleanup3, err := NewDockerClient(client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	nodeIdentity := NewNodeIdentity(app, store, dockerClient)
	observer := NewObserver(app, store, dockerClient)
	janitor := NewJanitor(app, store, appConfig)
	box, err := NewSecretsBox(app, appConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	daemonManager := NewDaemonManager(client)
	builder := NewBuilder(appConfig, store, client, daemonManager, app)
	queue := NewBuildQueue(app, appConfig, store, builder)
	resolver := NewPlacementResolver(store, dockerClient)
	engine := NewEngine(app, appConfig, store, client, resolver, box)
	server, err := NewHTTPServer(app, appConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	systemService := NewSystemService()
	grpcServer, err := NewGRPCServer(app, appConfig, systemService)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v := NewServices(app, store, nodeIdentity, observer, janitor, box, queue, builder, engine, server, grpcServer)
	v2 := NewServiceFactories()
	bootstrap := boot.New(preStartHooks, drainHooks, preStopHooks, postStopHooks, v, v2)
	return bootstrap, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
