package errcode

import "google.golang.org/grpc/codes"

// builtins 是首发码集。纪律：只增不复用——新码必须带 Source 锚点并在
// 生产代码出现（usage 反扫），预留码进 usage_test.go 豁免清单并在此注明。
var builtins = []Code{
	{
		ID:         "E_INTERNAL",
		Summary:    "Internal server error.",
		Suggestion: "Check fleetlyd logs for the matching error_id. If the error persists, report it with the error_id attached.",
		Source:     "internal/api/fleetlygrpc/mapping.go mapStateError (fallback)",
		GRPC:       codes.Internal,
	},
	{
		ID:         "E_NOT_FOUND",
		Summary:    "The requested resource does not exist.",
		Suggestion: "Check the resource id and list existing resources to confirm the target.",
		Source:     "internal/api/fleetlygrpc/mapping.go mapStateError",
		GRPC:       codes.NotFound,
	},
	{
		ID:         "E_ALREADY_EXISTS",
		Summary:    "A resource with the same unique key already exists.",
		Suggestion: "Choose a different name, or fetch the existing resource instead of creating a new one.",
		Source:     "internal/api/fleetlygrpc/mapping.go mapStateError (state.ErrAlreadyExists; producer restored in the 2026-10-01 batch-0 review after the REST 409 regression)",
		GRPC:       codes.AlreadyExists,
	},
	{
		ID:         "E_INVALID_ARGUMENT",
		Summary:    "The request payload is invalid.",
		Suggestion: "Fix the flagged field and retry. Field paths point at the exact input location.",
		Source:     "internal/spec spec.ValidationError → internal/api/fleetlygrpc/mapping.go mapValidationError",
		GRPC:       codes.InvalidArgument,
	},
	{
		ID:         "E_QUEUE_FULL",
		Summary:    "The deployment admission queue is full for this app.",
		Suggestion: "Retry after in-flight deployments finish, or cancel a queued deployment to free a slot.",
		Source:     "internal/engine/admission.go Submit (ADR-0016)",
		GRPC:       codes.ResourceExhausted,
	},
	{
		ID:         "E_NOT_CANCELLABLE",
		Summary:    "The deployment has reached a terminal state and can no longer be cancelled.",
		Suggestion: "Terminal states are facts, not actions; deploy a new revision instead.",
		Source:     "internal/engine/admission.go Cancel",
		GRPC:       codes.FailedPrecondition,
	},
	{
		ID:         "E_NO_BASELINE",
		Summary:    "The app has no successful deployment to roll back to.",
		Suggestion: "Deploy at least one revision successfully before rolling back.",
		Source:     "internal/engine/rollback.go Rollback",
		GRPC:       codes.FailedPrecondition,
	},
	{
		ID:         "E_CONFLICT",
		Summary:    "The operation conflicts with the resource's current state.",
		Suggestion: "Resolve the conflicting state named in the cause (cancel or wait for active work, remove referencing resources, or refresh after a concurrent change) and retry.",
		Source:     "internal/api/fleetlygrpc/mapping.go mapStateError (state.ErrConflict: CAS mismatch / FK RESTRICT); structure.go DeleteApp/DeleteProject (ADR-0023); REST maps 409 via assembly errcodeToHTTP",
		GRPC:       codes.FailedPrecondition,
	},
	{
		ID:         "E_QUOTA_EXCEEDED",
		Summary:    "A project-level quota has been reached.",
		Suggestion: "Remove unused entries of the quoted resource, or split the workload across projects.",
		Source:     "internal/api/fleetlygrpc/acceptance.go taskQuota/appQuota; structure.go configQuota (F0.17) / PutConfig",
		GRPC:       codes.ResourceExhausted,
	},
	{
		ID:         "E_RATE_LIMITED",
		Summary:    "The token has exhausted its create-request budget for the current rate window.",
		Suggestion: "Retry after retry_after_seconds (REST also carries Retry-After). Idempotent replays do not consume budget: reuse the same Idempotency-Key to safely re-fetch a completed response.",
		Source:     "internal/governance/ratelimit.go (ADR-0017 appendix A.2: per-token fixed window, in-memory, single-process control plane)",
		GRPC:       codes.ResourceExhausted,
	},
	{
		ID:         "E_CHANGE_FROZEN",
		Summary:    "A change freeze is active for the team owning this resource; the change verb is refused with the freeze reason.",
		Suggestion: "Read-only and stop verbs stay available during the freeze. An operator lifts it with 'fleetly freeze lift <id>' (the freeze_id context names the row).",
		Source:     "internal/governance/freeze.go (ADR-0017 appendix A.3: team-scoped change freeze, tsuru Block semantics)",
		GRPC:       codes.FailedPrecondition,
	},
	{
		ID:         "E_SECRET_UNAVAILABLE",
		Summary:    "The secret facility is unavailable or the referenced secret is missing.",
		Suggestion: "Create the missing secret or restore the master key under the data root keys/ directory.",
		Source:     "internal/api/fleetlygrpc/structure.go PutSecret / resolveMaterials",
		GRPC:       codes.FailedPrecondition,
	},
	{
		ID:         "E_UNAUTHENTICATED",
		Summary:    "The request carries no valid token.",
		Suggestion: "Log in with a valid token ('fleetly login'), or check that the token has not been revoked.",
		Source:     "internal/authn/interceptor.go guard",
		GRPC:       codes.Unauthenticated,
	},
	{
		ID:         "E_FORBIDDEN",
		Summary:    "The token lacks the scope required by this method.",
		Suggestion: "Use a token whose role grants the required resource:action scope, or ask an admin for one.",
		Source:     "internal/authn/interceptor.go guard (scopeSet.Satisfies)",
		GRPC:       codes.PermissionDenied,
	},
	{
		ID:         "E_INVALID_INVITATION",
		Summary:    "The invitation token is invalid, already used, or expired.",
		Suggestion: "Ask an admin for a fresh invitation; invitation tokens are single-use and time-boxed.",
		Source:     "internal/api/fleetlygrpc/invitations.go AcceptInvitation",
		GRPC:       codes.PermissionDenied,
	},
	{
		ID:         "E_INVALID_SIGNATURE",
		Summary:    "The webhook signature verification failed.",
		Suggestion: "Ensure the GitHub webhook secret matches the hook secret shown once by 'fleetly hooks set/rotate' (rotate the hook and update GitHub if the secret is lost).",
		Source:     "internal/api/fleetlygrpc/webhook.go ReceiveWebhook",
		GRPC:       codes.Unauthenticated,
	},
	{
		ID:         "E_IDEMPOTENCY_KEY_CONFLICT",
		Summary:    "The Idempotency-Key is already used by a different or in-progress request, or conflicts with the request's own idempotency_key field.",
		Suggestion: "Use a fresh key for each new request. A completed response replays for 24h under the same key and the same request body; an in-progress request returns this conflict until it completes.",
		Source:     "internal/idem/enforcer.go (ADR-0024: header form, single table, interceptor enforcement)",
		GRPC:       codes.AlreadyExists,
	},
	{
		ID:         "E_EVENTS_GONE",
		Summary:    "The requested event cursor is older than the earliest retained event (the retention window trimmed it).",
		Suggestion: "Resynchronize: re-read the current state of the resources you track (list endpoints), then continue from the last_seq reported by GetEventStatus.",
		Source:     "internal/api/fleetlygrpc/contexts.go EventsService (ADR-0026: retention window + 410 + snapshot resync)",
		GRPC:       codes.FailedPrecondition,
	},
	{
		ID:         "E_UPLOAD_TOO_LARGE",
		Summary:    "The uploaded source exceeds the per-upload size limit.",
		Suggestion: "Exclude build-irrelevant files from the directory (e.g. .git), or build from a git reference instead.",
		Source:     "internal/api/fleetlygrpc/uploads.go UploadSource (ADR-0019 appendix A.3: streaming byte budget, 512MiB default)",
		GRPC:       codes.ResourceExhausted,
	},
	{
		ID:         "E_UPLOAD_UNAVAILABLE",
		Summary:    "The uploaded source referenced by this deploy no longer has its blob on disk.",
		Suggestion: "The upload was likely affected by a retention sweep or a data-root migration; upload the source again and redeploy.",
		Source:     "internal/api/fleetlygrpc/delivery.go Deploy (ADR-0019 appendix A.5)",
		GRPC:       codes.FailedPrecondition,
	},
	{
		ID:         "E_PLATFORM_BACKUP_FAILED",
		Summary:    "The platform backup chain failed or is unavailable (restic missing, platform backup not configured, or the restic run failed).",
		Suggestion: "Install the pinned restic version and retry; a failed platform backup is a hard stop for the upgrade sequence (ADR-0015: backup precedes the swap). The platform.backup_failed event carries the chain detail.",
		Source:     "internal/api/fleetlygrpc/platform.go TriggerPlatformBackup/ListPlatformBackups (ADR-0039 decision 10; F2.3 upgrade precondition)",
		GRPC:       codes.FailedPrecondition,
	},
	{
		ID:         "E_EXEC_UNSUPPORTED",
		Summary:    "The runtime provider does not implement the exec sub-face.",
		Suggestion: "Exec sessions require a runtime with RuntimeExec implemented; this deployment's runtime cannot serve them. Diagnose via `fleetly nodes list` (relay_online shows per-node relay reachability where the sub-face exists).",
		Source:     "internal/api/fleetlygrpc/exec.go CreateExecSession (ADR-0049 decision 1: honest failure when the sub-face is absent, no degraded path)",
		GRPC:       codes.Unimplemented,
	},
	{
		ID:         "E_NODE_RELAY_OFFLINE",
		Summary:    "The target node has no connected relay, so the exec session cannot be routed to it.",
		Suggestion: "Run the relay command printed by `fleetly nodes enroll` on the affected node (idempotent; it also refreshes an outdated relay after a platform upgrade), then retry. `fleetly nodes list` shows relay_online per node.",
		Source:     "internal/engine/exec.go CreateSession (ADR-0049 decision 2: reverse-relay routing requires a live relay; nodes with zero inbound ports are reached only through their outbound relay)",
		GRPC:       codes.FailedPrecondition,
	},
	{
		ID:         "E_TEMPLATE_INVALID",
		Summary:    "An app template document failed to parse, render or validate.",
		Suggestion: "The error names the template field at fault. If the template came from a catalog refresh, the refresh pre-validation should have caught it; report the template name@version (in the message) with the error text.",
		Source:     "internal/api/fleetlygrpc/templates.go InstantiateTemplate (ADR-0050 decision 2: fail-closed render chain; refresh pre-validates the same entry points, so reaching this code means a template defect)",
		GRPC:       codes.InvalidArgument,
	},
	{
		ID:         "E_CATALOG_UNAVAILABLE",
		Summary:    "The template catalog refresh failed (fetch, digest verification or pre-validation).",
		Suggestion: "The served catalog is unchanged. Check the configured server.templates_catalog_url, that the endpoint serves catalog.json (manifest version 1 with per-template sha256 digests), and that every entry passes validation; the error text names the failing step.",
		Source:     "internal/api/fleetlygrpc/templates.go RefreshTemplates (ADR-0050 decision 4: fail-closed refresh — a bad catalog never replaces a working one)",
		GRPC:       codes.Unavailable,
	},
	{
		ID:         "E_BROWSE_DISABLED",
		Summary:    "The database browse face is not configured on this platform (browse.host_suffix empty).",
		Suggestion: "Browse sessions need a host suffix to mint session routes. Set browse.host_suffix (and browse.gateway_url) in the fleetlyd config, then restart; absence is an explicit off state, not a degraded mode (ADR-0051 decision 5).",
		Source:     "internal/api/fleetlygrpc/databases.go BrowseDatabase (ADR-0051 decision 5: empty host_suffix = face disabled, precise rejection)",
		GRPC:       codes.FailedPrecondition,
	},
	{
		ID:         "E_DATABASE_NOT_READY",
		Summary:    "The database is not running, so a browse session would serve a connection error page.",
		Suggestion: "Wait for the database to converge to running (`fleetly databases get` shows status); browse is refused for pending/stopped databases rather than serving an unusable browser.",
		Source:     "internal/api/fleetlygrpc/databases.go BrowseDatabase (ADR-0051 decision 1: acceptance requires a running target — honest refusal over a broken session)",
		GRPC:       codes.FailedPrecondition,
	},
	{
		ID:         "E_BROWSER_UNSUPPORTED",
		Summary:    "The database engine has no browse browser mapped in the dbbrowser registry.",
		Suggestion: "The engine-to-browser mapping (postgres/pgvector→pgweb, redis→redis-commander, mysql→adminer, mongo→mongoku) is total over the dbtemplate value set; reaching this code means a new engine was added without a browser adapter. Extend internal/engine/dbbrowser (ADR-0051 decision 3).",
		Source:     "internal/engine/dbbrowser For (ADR-0051 decision 3: registry totality is the acceptance contract; unmapped engine = honest failure)",
		GRPC:       codes.Unimplemented,
	},
}
