// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: fleetly/delivery/v1/delivery.proto

// Delivery 上下文（领域模型 §2）：源接入、构建、Revision 冻结与 Deployment
// 生命周期。Deploy 是一站式入口：两源归一化 → AppSpec 校验 → Revision
// 冻结（内容寻址复用）→ admission（ADR-0016）。

package deliveryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeploymentsService_Deploy_FullMethodName           = "/fleetly.delivery.v1.DeploymentsService/Deploy"
	DeploymentsService_GetDeployment_FullMethodName    = "/fleetly.delivery.v1.DeploymentsService/GetDeployment"
	DeploymentsService_ListDeployments_FullMethodName  = "/fleetly.delivery.v1.DeploymentsService/ListDeployments"
	DeploymentsService_CancelDeployment_FullMethodName = "/fleetly.delivery.v1.DeploymentsService/CancelDeployment"
	DeploymentsService_Rollback_FullMethodName         = "/fleetly.delivery.v1.DeploymentsService/Rollback"
)

// DeploymentsServiceClient is the client API for DeploymentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeploymentsServiceClient interface {
	// Deploy 归一化两源（镜像直投 / Compose 受控子集）并受理部署。
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error)
	GetDeployment(ctx context.Context, in *GetDeploymentRequest, opts ...grpc.CallOption) (*GetDeploymentResponse, error)
	ListDeployments(ctx context.Context, in *ListDeploymentsRequest, opts ...grpc.CallOption) (*ListDeploymentsResponse, error)
	CancelDeployment(ctx context.Context, in *CancelDeploymentRequest, opts ...grpc.CallOption) (*CancelDeploymentResponse, error)
	// Rollback 是一等动词（F0.11）：Revision Replay——空目标回上一成功基线。
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
}

type deploymentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentsServiceClient(cc grpc.ClientConnInterface) DeploymentsServiceClient {
	return &deploymentsServiceClient{cc}
}

func (c *deploymentsServiceClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, DeploymentsService_Deploy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsServiceClient) GetDeployment(ctx context.Context, in *GetDeploymentRequest, opts ...grpc.CallOption) (*GetDeploymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeploymentResponse)
	err := c.cc.Invoke(ctx, DeploymentsService_GetDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsServiceClient) ListDeployments(ctx context.Context, in *ListDeploymentsRequest, opts ...grpc.CallOption) (*ListDeploymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeploymentsResponse)
	err := c.cc.Invoke(ctx, DeploymentsService_ListDeployments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsServiceClient) CancelDeployment(ctx context.Context, in *CancelDeploymentRequest, opts ...grpc.CallOption) (*CancelDeploymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelDeploymentResponse)
	err := c.cc.Invoke(ctx, DeploymentsService_CancelDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentsServiceClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, DeploymentsService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeploymentsServiceServer is the server API for DeploymentsService service.
// All implementations must embed UnimplementedDeploymentsServiceServer
// for forward compatibility.
type DeploymentsServiceServer interface {
	// Deploy 归一化两源（镜像直投 / Compose 受控子集）并受理部署。
	Deploy(context.Context, *DeployRequest) (*DeployResponse, error)
	GetDeployment(context.Context, *GetDeploymentRequest) (*GetDeploymentResponse, error)
	ListDeployments(context.Context, *ListDeploymentsRequest) (*ListDeploymentsResponse, error)
	CancelDeployment(context.Context, *CancelDeploymentRequest) (*CancelDeploymentResponse, error)
	// Rollback 是一等动词（F0.11）：Revision Replay——空目标回上一成功基线。
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	mustEmbedUnimplementedDeploymentsServiceServer()
}

// UnimplementedDeploymentsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeploymentsServiceServer struct{}

func (UnimplementedDeploymentsServiceServer) Deploy(context.Context, *DeployRequest) (*DeployResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deploy not implemented")
}
func (UnimplementedDeploymentsServiceServer) GetDeployment(context.Context, *GetDeploymentRequest) (*GetDeploymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeployment not implemented")
}
func (UnimplementedDeploymentsServiceServer) ListDeployments(context.Context, *ListDeploymentsRequest) (*ListDeploymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeployments not implemented")
}
func (UnimplementedDeploymentsServiceServer) CancelDeployment(context.Context, *CancelDeploymentRequest) (*CancelDeploymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelDeployment not implemented")
}
func (UnimplementedDeploymentsServiceServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedDeploymentsServiceServer) mustEmbedUnimplementedDeploymentsServiceServer() {}
func (UnimplementedDeploymentsServiceServer) testEmbeddedByValue()                            {}

// UnsafeDeploymentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploymentsServiceServer will
// result in compilation errors.
type UnsafeDeploymentsServiceServer interface {
	mustEmbedUnimplementedDeploymentsServiceServer()
}

func RegisterDeploymentsServiceServer(s grpc.ServiceRegistrar, srv DeploymentsServiceServer) {
	// If the following call panics, it indicates UnimplementedDeploymentsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeploymentsService_ServiceDesc, srv)
}

func _DeploymentsService_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServiceServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentsService_Deploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServiceServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentsService_GetDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServiceServer).GetDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentsService_GetDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServiceServer).GetDeployment(ctx, req.(*GetDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentsService_ListDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeploymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServiceServer).ListDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentsService_ListDeployments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServiceServer).ListDeployments(ctx, req.(*ListDeploymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentsService_CancelDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServiceServer).CancelDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentsService_CancelDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServiceServer).CancelDeployment(ctx, req.(*CancelDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentsService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentsServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentsService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentsServiceServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeploymentsService_ServiceDesc is the grpc.ServiceDesc for DeploymentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeploymentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetly.delivery.v1.DeploymentsService",
	HandlerType: (*DeploymentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deploy",
			Handler:    _DeploymentsService_Deploy_Handler,
		},
		{
			MethodName: "GetDeployment",
			Handler:    _DeploymentsService_GetDeployment_Handler,
		},
		{
			MethodName: "ListDeployments",
			Handler:    _DeploymentsService_ListDeployments_Handler,
		},
		{
			MethodName: "CancelDeployment",
			Handler:    _DeploymentsService_CancelDeployment_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _DeploymentsService_Rollback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fleetly/delivery/v1/delivery.proto",
}

const (
	RevisionsService_ListRevisions_FullMethodName = "/fleetly.delivery.v1.RevisionsService/ListRevisions"
	RevisionsService_DiffRevisions_FullMethodName = "/fleetly.delivery.v1.RevisionsService/DiffRevisions"
)

// RevisionsServiceClient is the client API for RevisionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RevisionsServiceClient interface {
	ListRevisions(ctx context.Context, in *ListRevisionsRequest, opts ...grpc.CallOption) (*ListRevisionsResponse, error)
	// DiffRevisions 输出两条 Revision 的字段级差异（路径字典序）。
	DiffRevisions(ctx context.Context, in *DiffRevisionsRequest, opts ...grpc.CallOption) (*DiffRevisionsResponse, error)
}

type revisionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRevisionsServiceClient(cc grpc.ClientConnInterface) RevisionsServiceClient {
	return &revisionsServiceClient{cc}
}

func (c *revisionsServiceClient) ListRevisions(ctx context.Context, in *ListRevisionsRequest, opts ...grpc.CallOption) (*ListRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRevisionsResponse)
	err := c.cc.Invoke(ctx, RevisionsService_ListRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *revisionsServiceClient) DiffRevisions(ctx context.Context, in *DiffRevisionsRequest, opts ...grpc.CallOption) (*DiffRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffRevisionsResponse)
	err := c.cc.Invoke(ctx, RevisionsService_DiffRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RevisionsServiceServer is the server API for RevisionsService service.
// All implementations must embed UnimplementedRevisionsServiceServer
// for forward compatibility.
type RevisionsServiceServer interface {
	ListRevisions(context.Context, *ListRevisionsRequest) (*ListRevisionsResponse, error)
	// DiffRevisions 输出两条 Revision 的字段级差异（路径字典序）。
	DiffRevisions(context.Context, *DiffRevisionsRequest) (*DiffRevisionsResponse, error)
	mustEmbedUnimplementedRevisionsServiceServer()
}

// UnimplementedRevisionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRevisionsServiceServer struct{}

func (UnimplementedRevisionsServiceServer) ListRevisions(context.Context, *ListRevisionsRequest) (*ListRevisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRevisions not implemented")
}
func (UnimplementedRevisionsServiceServer) DiffRevisions(context.Context, *DiffRevisionsRequest) (*DiffRevisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiffRevisions not implemented")
}
func (UnimplementedRevisionsServiceServer) mustEmbedUnimplementedRevisionsServiceServer() {}
func (UnimplementedRevisionsServiceServer) testEmbeddedByValue()                          {}

// UnsafeRevisionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RevisionsServiceServer will
// result in compilation errors.
type UnsafeRevisionsServiceServer interface {
	mustEmbedUnimplementedRevisionsServiceServer()
}

func RegisterRevisionsServiceServer(s grpc.ServiceRegistrar, srv RevisionsServiceServer) {
	// If the following call panics, it indicates UnimplementedRevisionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RevisionsService_ServiceDesc, srv)
}

func _RevisionsService_ListRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevisionsServiceServer).ListRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevisionsService_ListRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevisionsServiceServer).ListRevisions(ctx, req.(*ListRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RevisionsService_DiffRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevisionsServiceServer).DiffRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevisionsService_DiffRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevisionsServiceServer).DiffRevisions(ctx, req.(*DiffRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RevisionsService_ServiceDesc is the grpc.ServiceDesc for RevisionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RevisionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetly.delivery.v1.RevisionsService",
	HandlerType: (*RevisionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRevisions",
			Handler:    _RevisionsService_ListRevisions_Handler,
		},
		{
			MethodName: "DiffRevisions",
			Handler:    _RevisionsService_DiffRevisions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fleetly/delivery/v1/delivery.proto",
}

const (
	BuildsService_ListBuilds_FullMethodName = "/fleetly.delivery.v1.BuildsService/ListBuilds"
)

// BuildsServiceClient is the client API for BuildsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuildsServiceClient interface {
	ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error)
}

type buildsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildsServiceClient(cc grpc.ClientConnInterface) BuildsServiceClient {
	return &buildsServiceClient{cc}
}

func (c *buildsServiceClient) ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBuildsResponse)
	err := c.cc.Invoke(ctx, BuildsService_ListBuilds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildsServiceServer is the server API for BuildsService service.
// All implementations must embed UnimplementedBuildsServiceServer
// for forward compatibility.
type BuildsServiceServer interface {
	ListBuilds(context.Context, *ListBuildsRequest) (*ListBuildsResponse, error)
	mustEmbedUnimplementedBuildsServiceServer()
}

// UnimplementedBuildsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuildsServiceServer struct{}

func (UnimplementedBuildsServiceServer) ListBuilds(context.Context, *ListBuildsRequest) (*ListBuildsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBuilds not implemented")
}
func (UnimplementedBuildsServiceServer) mustEmbedUnimplementedBuildsServiceServer() {}
func (UnimplementedBuildsServiceServer) testEmbeddedByValue()                       {}

// UnsafeBuildsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildsServiceServer will
// result in compilation errors.
type UnsafeBuildsServiceServer interface {
	mustEmbedUnimplementedBuildsServiceServer()
}

func RegisterBuildsServiceServer(s grpc.ServiceRegistrar, srv BuildsServiceServer) {
	// If the following call panics, it indicates UnimplementedBuildsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuildsService_ServiceDesc, srv)
}

func _BuildsService_ListBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildsServiceServer).ListBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildsService_ListBuilds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildsServiceServer).ListBuilds(ctx, req.(*ListBuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildsService_ServiceDesc is the grpc.ServiceDesc for BuildsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetly.delivery.v1.BuildsService",
	HandlerType: (*BuildsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBuilds",
			Handler:    _BuildsService_ListBuilds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fleetly/delivery/v1/delivery.proto",
}
