// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: fleetly/delivery/v1/registry.proto

// Registry 只读代理面（IA v3 二期⑤b）：受管镜像仓内容视图——/v2/_catalog
// 与 tags/list 按项目凭证代理（Registry 页二期视图的数据源；§5.1）。仓库
// 前纲 = <project_id>/<app_id> 双段小写（buildRepo 单源），catalog 按前纲
// 过滤、tags 校验归属——跨项目仓名不可达。内容面零状态迁移：纯读代理，
// 大小/推送时刻从 manifest 诚实解析（index 形态不可得字段留空值）。

package deliveryv1

import (
	_ "github.com/lynx-go/grpcapi/genproto/grpcapi/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRegistryCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegistryCatalogRequest) Reset() {
	*x = ListRegistryCatalogRequest{}
	mi := &file_fleetly_delivery_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegistryCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegistryCatalogRequest) ProtoMessage() {}

func (x *ListRegistryCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_delivery_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegistryCatalogRequest.ProtoReflect.Descriptor instead.
func (*ListRegistryCatalogRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_delivery_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ListRegistryCatalogRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListRegistryCatalogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repositories 是项目前纲下的仓名（全名含前纲，<project>/<app> 小写）。
	Repositories  []string `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegistryCatalogResponse) Reset() {
	*x = ListRegistryCatalogResponse{}
	mi := &file_fleetly_delivery_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegistryCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegistryCatalogResponse) ProtoMessage() {}

func (x *ListRegistryCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_delivery_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegistryCatalogResponse.ProtoReflect.Descriptor instead.
func (*ListRegistryCatalogResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_delivery_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *ListRegistryCatalogResponse) GetRepositories() []string {
	if x != nil {
		return x.Repositories
	}
	return nil
}

// RegistryTag 是一个 tag 的内容事实（大小 = manifest config+layers 描述符
// 之和，即压缩形态仓库占用；pushed_at 取 config created 注记，RFC3339）。
type RegistryTag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// digest 是 manifest 内容寻址（sha256:…；from_build 下发的拉取锚）。
	Digest        string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	SizeBytes     int64  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	PushedAt      string `protobuf:"bytes,4,opt,name=pushed_at,json=pushedAt,proto3" json:"pushed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryTag) Reset() {
	*x = RegistryTag{}
	mi := &file_fleetly_delivery_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryTag) ProtoMessage() {}

func (x *RegistryTag) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_delivery_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryTag.ProtoReflect.Descriptor instead.
func (*RegistryTag) Descriptor() ([]byte, []int) {
	return file_fleetly_delivery_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegistryTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistryTag) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *RegistryTag) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *RegistryTag) GetPushedAt() string {
	if x != nil {
		return x.PushedAt
	}
	return ""
}

type ListRegistryTagsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// repository 是仓名（须落在该项目前纲下——越纲按 not found 拒绝）。
	Repository    string `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegistryTagsRequest) Reset() {
	*x = ListRegistryTagsRequest{}
	mi := &file_fleetly_delivery_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegistryTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegistryTagsRequest) ProtoMessage() {}

func (x *ListRegistryTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_delivery_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegistryTagsRequest.ProtoReflect.Descriptor instead.
func (*ListRegistryTagsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_delivery_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *ListRegistryTagsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListRegistryTagsRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type ListRegistryTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Tags          []*RegistryTag         `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegistryTagsResponse) Reset() {
	*x = ListRegistryTagsResponse{}
	mi := &file_fleetly_delivery_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegistryTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegistryTagsResponse) ProtoMessage() {}

func (x *ListRegistryTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_delivery_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegistryTagsResponse.ProtoReflect.Descriptor instead.
func (*ListRegistryTagsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_delivery_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *ListRegistryTagsResponse) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ListRegistryTagsResponse) GetTags() []*RegistryTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_fleetly_delivery_v1_registry_proto protoreflect.FileDescriptor

const file_fleetly_delivery_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\"fleetly/delivery/v1/registry.proto\x12\x13fleetly.delivery.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x16grpcapi/v1/authz.proto\";\n" +
	"\x1aListRegistryCatalogRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"A\n" +
	"\x1bListRegistryCatalogResponse\x12\"\n" +
	"\frepositories\x18\x01 \x03(\tR\frepositories\"u\n" +
	"\vRegistryTag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tpushed_at\x18\x04 \x01(\tR\bpushedAt\"X\n" +
	"\x17ListRegistryTagsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\"p\n" +
	"\x18ListRegistryTagsResponse\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x124\n" +
	"\x04tags\x18\x02 \x03(\v2 .fleetly.delivery.v1.RegistryTagR\x04tags2\xf4\x02\n" +
	"\x0fRegistryService\x12\xaa\x01\n" +
	"\x13ListRegistryCatalog\x12/.fleetly.delivery.v1.ListRegistryCatalogRequest\x1a0.fleetly.delivery.v1.ListRegistryCatalogResponse\"0\xea\xc4\x19\x10\b\x03\"\f\n" +
	"\bregistry\x10\x01\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/registry/catalog\x12\xab\x01\n" +
	"\x10ListRegistryTags\x12,.fleetly.delivery.v1.ListRegistryTagsRequest\x1a-.fleetly.delivery.v1.ListRegistryTagsResponse\":\xea\xc4\x19\x10\b\x03\"\f\n" +
	"\bregistry\x10\x01\x82\xd3\xe4\x93\x02 \x12\x1e/v1/registry/{repository}/tags\x1a\x06\xf2\xc4\x19\x02\b\x03BGZEgithub.com/fleetlyrun/fleetly/genproto/fleetly/delivery/v1;deliveryv1b\x06proto3"

var (
	file_fleetly_delivery_v1_registry_proto_rawDescOnce sync.Once
	file_fleetly_delivery_v1_registry_proto_rawDescData []byte
)

func file_fleetly_delivery_v1_registry_proto_rawDescGZIP() []byte {
	file_fleetly_delivery_v1_registry_proto_rawDescOnce.Do(func() {
		file_fleetly_delivery_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_delivery_v1_registry_proto_rawDesc), len(file_fleetly_delivery_v1_registry_proto_rawDesc)))
	})
	return file_fleetly_delivery_v1_registry_proto_rawDescData
}

var file_fleetly_delivery_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fleetly_delivery_v1_registry_proto_goTypes = []any{
	(*ListRegistryCatalogRequest)(nil),  // 0: fleetly.delivery.v1.ListRegistryCatalogRequest
	(*ListRegistryCatalogResponse)(nil), // 1: fleetly.delivery.v1.ListRegistryCatalogResponse
	(*RegistryTag)(nil),                 // 2: fleetly.delivery.v1.RegistryTag
	(*ListRegistryTagsRequest)(nil),     // 3: fleetly.delivery.v1.ListRegistryTagsRequest
	(*ListRegistryTagsResponse)(nil),    // 4: fleetly.delivery.v1.ListRegistryTagsResponse
}
var file_fleetly_delivery_v1_registry_proto_depIdxs = []int32{
	2, // 0: fleetly.delivery.v1.ListRegistryTagsResponse.tags:type_name -> fleetly.delivery.v1.RegistryTag
	0, // 1: fleetly.delivery.v1.RegistryService.ListRegistryCatalog:input_type -> fleetly.delivery.v1.ListRegistryCatalogRequest
	3, // 2: fleetly.delivery.v1.RegistryService.ListRegistryTags:input_type -> fleetly.delivery.v1.ListRegistryTagsRequest
	1, // 3: fleetly.delivery.v1.RegistryService.ListRegistryCatalog:output_type -> fleetly.delivery.v1.ListRegistryCatalogResponse
	4, // 4: fleetly.delivery.v1.RegistryService.ListRegistryTags:output_type -> fleetly.delivery.v1.ListRegistryTagsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fleetly_delivery_v1_registry_proto_init() }
func file_fleetly_delivery_v1_registry_proto_init() {
	if File_fleetly_delivery_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_delivery_v1_registry_proto_rawDesc), len(file_fleetly_delivery_v1_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetly_delivery_v1_registry_proto_goTypes,
		DependencyIndexes: file_fleetly_delivery_v1_registry_proto_depIdxs,
		MessageInfos:      file_fleetly_delivery_v1_registry_proto_msgTypes,
	}.Build()
	File_fleetly_delivery_v1_registry_proto = out.File
	file_fleetly_delivery_v1_registry_proto_goTypes = nil
	file_fleetly_delivery_v1_registry_proto_depIdxs = nil
}
