// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: fleetly/identity/v1/identity.proto

// Identity & Access 上下文（领域模型 §2）：User/Team/Role/Token/Invitation
// 与审计查询面。Scope = `resource:action`（write 蕴含 read，admin 蕴含
// write）；Token 经 Team 内的 Role 获得 Scope（CONTEXT.md 词汇冻结）。

package identityv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/lynx-go/grpcapi/genproto/grpcapi/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WhoAmI 是 login 验证与 CLI 调试入口：返回当前 Token 的身份投影。
type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

type WhoAmIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenName     string                 `protobuf:"bytes,2,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	TeamId        string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,5,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,7,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Scopes        []string               `protobuf:"bytes,8,rep,name=scopes,proto3" json:"scopes,omitempty"` // colon 形态（resource:action），蕴含未展开
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *WhoAmIResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *WhoAmIResponse) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *WhoAmIResponse) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *WhoAmIResponse) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *WhoAmIResponse) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *WhoAmIResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WhoAmIResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *WhoAmIResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` // 归属 Team（缺省 default）
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // Team 内授予的 Role
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreateUserRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{7}
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{10}
}

type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{11}
}

func (x *Team) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamResponse) Reset() {
	*x = CreateTeamResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamResponse) ProtoMessage() {}

func (x *CreateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type GetTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamRequest.ProtoReflect.Descriptor instead.
func (*GetTeamRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{14}
}

func (x *GetTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamResponse) Reset() {
	*x = GetTeamResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamResponse) ProtoMessage() {}

func (x *GetTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamResponse.ProtoReflect.Descriptor instead.
func (*GetTeamResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{15}
}

func (x *GetTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type ListTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsRequest) Reset() {
	*x = ListTeamsRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsRequest) ProtoMessage() {}

func (x *ListTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsRequest.ProtoReflect.Descriptor instead.
func (*ListTeamsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{16}
}

type ListTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsResponse) Reset() {
	*x = ListTeamsResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsResponse) ProtoMessage() {}

func (x *ListTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{17}
}

func (x *ListTeamsResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

type DeleteTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamRequest) Reset() {
	*x = DeleteTeamRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamRequest) ProtoMessage() {}

func (x *DeleteTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamResponse) Reset() {
	*x = DeleteTeamResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamResponse) ProtoMessage() {}

func (x *DeleteTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{19}
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` // 空 = 平台级内置模板
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Builtin       bool                   `protobuf:"varint,4,opt,name=builtin,proto3" json:"builtin,omitempty"`
	Scopes        []string               `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"` // colon 形态（resource:action）
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{20}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetBuiltin() bool {
	if x != nil {
		return x.Builtin
	}
	return false
}

func (x *Role) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *Role) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` // 自定义 Role 属于某 Team
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`               // colon 形态；write⇒read 在执法点展开
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{21}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreateRoleRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{22}
}

func (x *CreateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{23}
}

func (x *GetRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{24}
}

func (x *GetRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{25}
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{26}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{28}
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TeamId        string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 可空：无属主用户的 Token（Agent/CI）
	RoleId        string                 `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Prefix        string                 `protobuf:"bytes,6,opt,name=prefix,proto3" json:"prefix,omitempty"` // 明文前缀（泄露识别）；完整明文不回显
	Revoked       bool                   `protobuf:"varint,7,opt,name=revoked,proto3" json:"revoked,omitempty"`
	LastUsedAt    string                 `protobuf:"bytes,8,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{29}
}

func (x *Token) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Token) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Token) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Token) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Token) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Token) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Token) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *Token) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

func (x *Token) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 可空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{30}
}

func (x *CreateTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTokenRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreateTokenRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *CreateTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// CreateTokenResponse 是明文唯一出现点（创建响应一次；之后只存 sha256）。
type CreateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"` // 完整明文，仅此一次
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{31}
}

func (x *CreateTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CreateTokenResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{32}
}

func (x *GetTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{33}
}

func (x *GetTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type ListTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{34}
}

type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*Token               `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{35}
}

func (x *ListTokensResponse) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{36}
}

func (x *RevokeTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{37}
}

func (x *RevokeTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type Invitation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // 操作者（user:<name>/token:<name>）
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ConsumedAt    string                 `protobuf:"bytes,6,opt,name=consumed_at,json=consumedAt,proto3" json:"consumed_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{38}
}

func (x *Invitation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invitation) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Invitation) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Invitation) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Invitation) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Invitation) GetConsumedAt() string {
	if x != nil {
		return x.ConsumedAt
	}
	return ""
}

func (x *Invitation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Ttl           string                 `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"` // 时长（如 "24h"；缺省 24h，上限 168h）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvitationRequest) Reset() {
	*x = CreateInvitationRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvitationRequest) ProtoMessage() {}

func (x *CreateInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvitationRequest.ProtoReflect.Descriptor instead.
func (*CreateInvitationRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{39}
}

func (x *CreateInvitationRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreateInvitationRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *CreateInvitationRequest) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

// CreateInvitationResponse 同 Token：邀请明文仅此一次。
type CreateInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitation    *Invitation            `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvitationResponse) Reset() {
	*x = CreateInvitationResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvitationResponse) ProtoMessage() {}

func (x *CreateInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvitationResponse.ProtoReflect.Descriptor instead.
func (*CreateInvitationResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{40}
}

func (x *CreateInvitationResponse) GetInvitation() *Invitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

func (x *CreateInvitationResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type ListInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsRequest) Reset() {
	*x = ListInvitationsRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsRequest) ProtoMessage() {}

func (x *ListInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsRequest.ProtoReflect.Descriptor instead.
func (*ListInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{41}
}

type ListInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitations   []*Invitation          `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsResponse) Reset() {
	*x = ListInvitationsResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsResponse) ProtoMessage() {}

func (x *ListInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsResponse.ProtoReflect.Descriptor instead.
func (*ListInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{42}
}

func (x *ListInvitationsResponse) GetInvitations() []*Invitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

type AcceptInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"` // 邀请 Token 明文（被邀请者持信物）
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationRequest) Reset() {
	*x = AcceptInvitationRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationRequest) ProtoMessage() {}

func (x *AcceptInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationRequest.ProtoReflect.Descriptor instead.
func (*AcceptInvitationRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{43}
}

func (x *AcceptInvitationRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AcceptInvitationRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type AcceptInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationResponse) Reset() {
	*x = AcceptInvitationResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationResponse) ProtoMessage() {}

func (x *AcceptInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationResponse.ProtoReflect.Descriptor instead.
func (*AcceptInvitationResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{44}
}

func (x *AcceptInvitationResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // manual|api|cli|webhook|schedule|system
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	BeforeFp      string                 `protobuf:"bytes,6,opt,name=before_fp,json=beforeFp,proto3" json:"before_fp,omitempty"`
	AfterFp       string                 `protobuf:"bytes,7,opt,name=after_fp,json=afterFp,proto3" json:"after_fp,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{45}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEntry) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditEntry) GetBeforeFp() string {
	if x != nil {
		return x.BeforeFp
	}
	return ""
}

func (x *AuditEntry) GetAfterFp() string {
	if x != nil {
		return x.AfterFp
	}
	return ""
}

func (x *AuditEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`     // manual|api|cli|webhook|schedule|system
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`     // 前缀过滤（如 "token."）
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"` // 精确过滤（如 "project/<id>"）
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`      // 上界 1000
	Actor         string                 `protobuf:"bytes,5,opt,name=actor,proto3" json:"actor,omitempty"`       // 精确过滤（user:<name>/token:<name>）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditRequest) Reset() {
	*x = ListAuditRequest{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditRequest) ProtoMessage() {}

func (x *ListAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditRequest.ProtoReflect.Descriptor instead.
func (*ListAuditRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{46}
}

func (x *ListAuditRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListAuditRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListAuditRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ListAuditRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuditRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type ListAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditResponse) Reset() {
	*x = ListAuditResponse{}
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditResponse) ProtoMessage() {}

func (x *ListAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_identity_v1_identity_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditResponse.ProtoReflect.Descriptor instead.
func (*ListAuditResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_identity_v1_identity_proto_rawDescGZIP(), []int{47}
}

func (x *ListAuditResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_fleetly_identity_v1_identity_proto protoreflect.FileDescriptor

const file_fleetly_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\"fleetly/identity/v1/identity.proto\x12\x13fleetly.identity.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x16grpcapi/v1/authz.proto\"\x0f\n" +
	"\rWhoAmIRequest\"\xe7\x01\n" +
	"\x0eWhoAmIResponse\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x1d\n" +
	"\n" +
	"token_name\x18\x02 \x01(\tR\ttokenName\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\tR\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x05 \x01(\tR\broleName\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\a \x01(\tR\buserName\x12\x16\n" +
	"\x06scopes\x18\b \x03(\tR\x06scopes\"I\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"Y\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\"C\n" +
	"\x12CreateUserResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.fleetly.identity.v1.UserR\x04user\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x0fGetUserResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.fleetly.identity.v1.UserR\x04user\"\x12\n" +
	"\x10ListUsersRequest\"D\n" +
	"\x11ListUsersResponse\x12/\n" +
	"\x05users\x18\x01 \x03(\v2\x19.fleetly.identity.v1.UserR\x05users\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteUserResponse\"I\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"'\n" +
	"\x11CreateTeamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"C\n" +
	"\x12CreateTeamResponse\x12-\n" +
	"\x04team\x18\x01 \x01(\v2\x19.fleetly.identity.v1.TeamR\x04team\" \n" +
	"\x0eGetTeamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x0fGetTeamResponse\x12-\n" +
	"\x04team\x18\x01 \x01(\v2\x19.fleetly.identity.v1.TeamR\x04team\"\x12\n" +
	"\x10ListTeamsRequest\"D\n" +
	"\x11ListTeamsResponse\x12/\n" +
	"\x05teams\x18\x01 \x03(\v2\x19.fleetly.identity.v1.TeamR\x05teams\"#\n" +
	"\x11DeleteTeamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteTeamResponse\"\x94\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\abuiltin\x18\x04 \x01(\bR\abuiltin\x12\x16\n" +
	"\x06scopes\x18\x05 \x03(\tR\x06scopes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"X\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\"C\n" +
	"\x12CreateRoleResponse\x12-\n" +
	"\x04role\x18\x01 \x01(\v2\x19.fleetly.identity.v1.RoleR\x04role\" \n" +
	"\x0eGetRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x0fGetRoleResponse\x12-\n" +
	"\x04role\x18\x01 \x01(\v2\x19.fleetly.identity.v1.RoleR\x04role\"\x12\n" +
	"\x10ListRolesRequest\"D\n" +
	"\x11ListRolesResponse\x12/\n" +
	"\x05roles\x18\x01 \x03(\v2\x19.fleetly.identity.v1.RoleR\x05roles\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteRoleResponse\"\xe9\x01\n" +
	"\x05Token\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\tR\x06roleId\x12\x16\n" +
	"\x06prefix\x18\x06 \x01(\tR\x06prefix\x12\x18\n" +
	"\arevoked\x18\a \x01(\bR\arevoked\x12 \n" +
	"\flast_used_at\x18\b \x01(\tR\n" +
	"lastUsedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"s\n" +
	"\x12CreateTokenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"_\n" +
	"\x13CreateTokenResponse\x120\n" +
	"\x05token\x18\x01 \x01(\v2\x1a.fleetly.identity.v1.TokenR\x05token\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"!\n" +
	"\x0fGetTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x10GetTokenResponse\x120\n" +
	"\x05token\x18\x01 \x01(\v2\x1a.fleetly.identity.v1.TokenR\x05token\"\x13\n" +
	"\x11ListTokensRequest\"H\n" +
	"\x12ListTokensResponse\x122\n" +
	"\x06tokens\x18\x01 \x03(\v2\x1a.fleetly.identity.v1.TokenR\x06tokens\"$\n" +
	"\x12RevokeTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x13RevokeTokenResponse\x120\n" +
	"\x05token\x18\x01 \x01(\v2\x1a.fleetly.identity.v1.TokenR\x05token\"\xcc\x01\n" +
	"\n" +
	"Invitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\x12\x1f\n" +
	"\vconsumed_at\x18\x06 \x01(\tR\n" +
	"consumedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"]\n" +
	"\x17CreateInvitationRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\tR\x03ttl\"s\n" +
	"\x18CreateInvitationResponse\x12?\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2\x1f.fleetly.identity.v1.InvitationR\n" +
	"invitation\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"\x18\n" +
	"\x16ListInvitationsRequest\"\\\n" +
	"\x17ListInvitationsResponse\x12A\n" +
	"\vinvitations\x18\x01 \x03(\v2\x1f.fleetly.identity.v1.InvitationR\vinvitations\"N\n" +
	"\x17AcceptInvitationRequest\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"I\n" +
	"\x18AcceptInvitationResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.fleetly.identity.v1.UserR\x04user\"\xd5\x01\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x05 \x01(\tR\bresource\x12\x1b\n" +
	"\tbefore_fp\x18\x06 \x01(\tR\bbeforeFp\x12\x19\n" +
	"\bafter_fp\x18\a \x01(\tR\aafterFp\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\x8a\x01\n" +
	"\x10ListAuditRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05actor\x18\x05 \x01(\tR\x05actor\"N\n" +
	"\x11ListAuditResponse\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.fleetly.identity.v1.AuditEntryR\aentries2\x92\x05\n" +
	"\fUsersService\x12k\n" +
	"\x06WhoAmI\x12\".fleetly.identity.v1.WhoAmIRequest\x1a#.fleetly.identity.v1.WhoAmIResponse\"\x18\xea\xc4\x19\x02\b\x01\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/whoami\x12\x84\x01\n" +
	"\n" +
	"CreateUser\x12&.fleetly.identity.v1.CreateUserRequest\x1a'.fleetly.identity.v1.CreateUserResponse\"%\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05users\x10\x02\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12}\n" +
	"\aGetUser\x12#.fleetly.identity.v1.GetUserRequest\x1a$.fleetly.identity.v1.GetUserResponse\"'\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05users\x10\x01\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/users/{id}\x12~\n" +
	"\tListUsers\x12%.fleetly.identity.v1.ListUsersRequest\x1a&.fleetly.identity.v1.ListUsersResponse\"\"\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05users\x10\x01\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12\x86\x01\n" +
	"\n" +
	"DeleteUser\x12&.fleetly.identity.v1.DeleteUserRequest\x1a'.fleetly.identity.v1.DeleteUserResponse\"'\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05users\x10\x03\x82\xd3\xe4\x93\x02\x10*\x0e/v1/users/{id}\x1a\x06\xf2\xc4\x19\x02\b\x032\xa5\x04\n" +
	"\fTeamsService\x12\x84\x01\n" +
	"\n" +
	"CreateTeam\x12&.fleetly.identity.v1.CreateTeamRequest\x1a'.fleetly.identity.v1.CreateTeamResponse\"%\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05teams\x10\x02\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/teams\x12}\n" +
	"\aGetTeam\x12#.fleetly.identity.v1.GetTeamRequest\x1a$.fleetly.identity.v1.GetTeamResponse\"'\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05teams\x10\x01\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/teams/{id}\x12~\n" +
	"\tListTeams\x12%.fleetly.identity.v1.ListTeamsRequest\x1a&.fleetly.identity.v1.ListTeamsResponse\"\"\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05teams\x10\x01\x82\xd3\xe4\x93\x02\v\x12\t/v1/teams\x12\x86\x01\n" +
	"\n" +
	"DeleteTeam\x12&.fleetly.identity.v1.DeleteTeamRequest\x1a'.fleetly.identity.v1.DeleteTeamResponse\"'\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05teams\x10\x03\x82\xd3\xe4\x93\x02\x10*\x0e/v1/teams/{id}\x1a\x06\xf2\xc4\x19\x02\b\x032\xa5\x04\n" +
	"\fRolesService\x12\x84\x01\n" +
	"\n" +
	"CreateRole\x12&.fleetly.identity.v1.CreateRoleRequest\x1a'.fleetly.identity.v1.CreateRoleResponse\"%\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05roles\x10\x02\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/roles\x12}\n" +
	"\aGetRole\x12#.fleetly.identity.v1.GetRoleRequest\x1a$.fleetly.identity.v1.GetRoleResponse\"'\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05roles\x10\x01\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/roles/{id}\x12~\n" +
	"\tListRoles\x12%.fleetly.identity.v1.ListRolesRequest\x1a&.fleetly.identity.v1.ListRolesResponse\"\"\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05roles\x10\x01\x82\xd3\xe4\x93\x02\v\x12\t/v1/roles\x12\x86\x01\n" +
	"\n" +
	"DeleteRole\x12&.fleetly.identity.v1.DeleteRoleRequest\x1a'.fleetly.identity.v1.DeleteRoleResponse\"'\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05roles\x10\x03\x82\xd3\xe4\x93\x02\x10*\x0e/v1/roles/{id}\x1a\x06\xf2\xc4\x19\x02\b\x032\xc6\x04\n" +
	"\rTokensService\x12\x89\x01\n" +
	"\vCreateToken\x12'.fleetly.identity.v1.CreateTokenRequest\x1a(.fleetly.identity.v1.CreateTokenResponse\"'\xea\xc4\x19\x0e\b\x03\"\n" +
	"\n" +
	"\x06tokens\x10\x02\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/tokens\x12\x82\x01\n" +
	"\bGetToken\x12$.fleetly.identity.v1.GetTokenRequest\x1a%.fleetly.identity.v1.GetTokenResponse\")\xea\xc4\x19\x0e\b\x03\"\n" +
	"\n" +
	"\x06tokens\x10\x01\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/tokens/{id}\x12\x83\x01\n" +
	"\n" +
	"ListTokens\x12&.fleetly.identity.v1.ListTokensRequest\x1a'.fleetly.identity.v1.ListTokensResponse\"$\xea\xc4\x19\x0e\b\x03\"\n" +
	"\n" +
	"\x06tokens\x10\x01\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/tokens\x12\x95\x01\n" +
	"\vRevokeToken\x12'.fleetly.identity.v1.RevokeTokenRequest\x1a(.fleetly.identity.v1.RevokeTokenResponse\"3\xea\xc4\x19\x0e\b\x03\"\n" +
	"\n" +
	"\x06tokens\x10\x03\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/tokens/{id}/revoke\x1a\x06\xf2\xc4\x19\x02\b\x032\xfb\x03\n" +
	"\x12InvitationsService\x12\xa2\x01\n" +
	"\x10CreateInvitation\x12,.fleetly.identity.v1.CreateInvitationRequest\x1a-.fleetly.identity.v1.CreateInvitationResponse\"1\xea\xc4\x19\x13\b\x03\"\x0f\n" +
	"\vinvitations\x10\x02\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/invitations\x12\x9c\x01\n" +
	"\x0fListInvitations\x12+.fleetly.identity.v1.ListInvitationsRequest\x1a,.fleetly.identity.v1.ListInvitationsResponse\".\xea\xc4\x19\x13\b\x03\"\x0f\n" +
	"\vinvitations\x10\x01\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/invitations\x12\x98\x01\n" +
	"\x10AcceptInvitation\x12,.fleetly.identity.v1.AcceptInvitationRequest\x1a-.fleetly.identity.v1.AcceptInvitationResponse\"'\xea\xc4\x19\x02\b\x01\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/invitations/accept\x1a\x06\xf2\xc4\x19\x02\b\x032\x9b\x01\n" +
	"\x11AuditQueryService\x12~\n" +
	"\tListAudit\x12%.fleetly.identity.v1.ListAuditRequest\x1a&.fleetly.identity.v1.ListAuditResponse\"\"\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05audit\x10\x01\x82\xd3\xe4\x93\x02\v\x12\t/v1/audit\x1a\x06\xf2\xc4\x19\x02\b\x03B\x9c\x01\x92ARRP\n" +
	"\adefault\x12E\n" +
	"\x1dAn unexpected error response.\x12$\n" +
	"\"\x1a .fleetly.shared.v1.ErrorResponseZEgithub.com/fleetlyrun/fleetly/genproto/fleetly/identity/v1;identityv1b\x06proto3"

var (
	file_fleetly_identity_v1_identity_proto_rawDescOnce sync.Once
	file_fleetly_identity_v1_identity_proto_rawDescData []byte
)

func file_fleetly_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_fleetly_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_fleetly_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_identity_v1_identity_proto_rawDesc), len(file_fleetly_identity_v1_identity_proto_rawDesc)))
	})
	return file_fleetly_identity_v1_identity_proto_rawDescData
}

var file_fleetly_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 48)
var file_fleetly_identity_v1_identity_proto_goTypes = []any{
	(*WhoAmIRequest)(nil),            // 0: fleetly.identity.v1.WhoAmIRequest
	(*WhoAmIResponse)(nil),           // 1: fleetly.identity.v1.WhoAmIResponse
	(*User)(nil),                     // 2: fleetly.identity.v1.User
	(*CreateUserRequest)(nil),        // 3: fleetly.identity.v1.CreateUserRequest
	(*CreateUserResponse)(nil),       // 4: fleetly.identity.v1.CreateUserResponse
	(*GetUserRequest)(nil),           // 5: fleetly.identity.v1.GetUserRequest
	(*GetUserResponse)(nil),          // 6: fleetly.identity.v1.GetUserResponse
	(*ListUsersRequest)(nil),         // 7: fleetly.identity.v1.ListUsersRequest
	(*ListUsersResponse)(nil),        // 8: fleetly.identity.v1.ListUsersResponse
	(*DeleteUserRequest)(nil),        // 9: fleetly.identity.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),       // 10: fleetly.identity.v1.DeleteUserResponse
	(*Team)(nil),                     // 11: fleetly.identity.v1.Team
	(*CreateTeamRequest)(nil),        // 12: fleetly.identity.v1.CreateTeamRequest
	(*CreateTeamResponse)(nil),       // 13: fleetly.identity.v1.CreateTeamResponse
	(*GetTeamRequest)(nil),           // 14: fleetly.identity.v1.GetTeamRequest
	(*GetTeamResponse)(nil),          // 15: fleetly.identity.v1.GetTeamResponse
	(*ListTeamsRequest)(nil),         // 16: fleetly.identity.v1.ListTeamsRequest
	(*ListTeamsResponse)(nil),        // 17: fleetly.identity.v1.ListTeamsResponse
	(*DeleteTeamRequest)(nil),        // 18: fleetly.identity.v1.DeleteTeamRequest
	(*DeleteTeamResponse)(nil),       // 19: fleetly.identity.v1.DeleteTeamResponse
	(*Role)(nil),                     // 20: fleetly.identity.v1.Role
	(*CreateRoleRequest)(nil),        // 21: fleetly.identity.v1.CreateRoleRequest
	(*CreateRoleResponse)(nil),       // 22: fleetly.identity.v1.CreateRoleResponse
	(*GetRoleRequest)(nil),           // 23: fleetly.identity.v1.GetRoleRequest
	(*GetRoleResponse)(nil),          // 24: fleetly.identity.v1.GetRoleResponse
	(*ListRolesRequest)(nil),         // 25: fleetly.identity.v1.ListRolesRequest
	(*ListRolesResponse)(nil),        // 26: fleetly.identity.v1.ListRolesResponse
	(*DeleteRoleRequest)(nil),        // 27: fleetly.identity.v1.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),       // 28: fleetly.identity.v1.DeleteRoleResponse
	(*Token)(nil),                    // 29: fleetly.identity.v1.Token
	(*CreateTokenRequest)(nil),       // 30: fleetly.identity.v1.CreateTokenRequest
	(*CreateTokenResponse)(nil),      // 31: fleetly.identity.v1.CreateTokenResponse
	(*GetTokenRequest)(nil),          // 32: fleetly.identity.v1.GetTokenRequest
	(*GetTokenResponse)(nil),         // 33: fleetly.identity.v1.GetTokenResponse
	(*ListTokensRequest)(nil),        // 34: fleetly.identity.v1.ListTokensRequest
	(*ListTokensResponse)(nil),       // 35: fleetly.identity.v1.ListTokensResponse
	(*RevokeTokenRequest)(nil),       // 36: fleetly.identity.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),      // 37: fleetly.identity.v1.RevokeTokenResponse
	(*Invitation)(nil),               // 38: fleetly.identity.v1.Invitation
	(*CreateInvitationRequest)(nil),  // 39: fleetly.identity.v1.CreateInvitationRequest
	(*CreateInvitationResponse)(nil), // 40: fleetly.identity.v1.CreateInvitationResponse
	(*ListInvitationsRequest)(nil),   // 41: fleetly.identity.v1.ListInvitationsRequest
	(*ListInvitationsResponse)(nil),  // 42: fleetly.identity.v1.ListInvitationsResponse
	(*AcceptInvitationRequest)(nil),  // 43: fleetly.identity.v1.AcceptInvitationRequest
	(*AcceptInvitationResponse)(nil), // 44: fleetly.identity.v1.AcceptInvitationResponse
	(*AuditEntry)(nil),               // 45: fleetly.identity.v1.AuditEntry
	(*ListAuditRequest)(nil),         // 46: fleetly.identity.v1.ListAuditRequest
	(*ListAuditResponse)(nil),        // 47: fleetly.identity.v1.ListAuditResponse
}
var file_fleetly_identity_v1_identity_proto_depIdxs = []int32{
	2,  // 0: fleetly.identity.v1.CreateUserResponse.user:type_name -> fleetly.identity.v1.User
	2,  // 1: fleetly.identity.v1.GetUserResponse.user:type_name -> fleetly.identity.v1.User
	2,  // 2: fleetly.identity.v1.ListUsersResponse.users:type_name -> fleetly.identity.v1.User
	11, // 3: fleetly.identity.v1.CreateTeamResponse.team:type_name -> fleetly.identity.v1.Team
	11, // 4: fleetly.identity.v1.GetTeamResponse.team:type_name -> fleetly.identity.v1.Team
	11, // 5: fleetly.identity.v1.ListTeamsResponse.teams:type_name -> fleetly.identity.v1.Team
	20, // 6: fleetly.identity.v1.CreateRoleResponse.role:type_name -> fleetly.identity.v1.Role
	20, // 7: fleetly.identity.v1.GetRoleResponse.role:type_name -> fleetly.identity.v1.Role
	20, // 8: fleetly.identity.v1.ListRolesResponse.roles:type_name -> fleetly.identity.v1.Role
	29, // 9: fleetly.identity.v1.CreateTokenResponse.token:type_name -> fleetly.identity.v1.Token
	29, // 10: fleetly.identity.v1.GetTokenResponse.token:type_name -> fleetly.identity.v1.Token
	29, // 11: fleetly.identity.v1.ListTokensResponse.tokens:type_name -> fleetly.identity.v1.Token
	29, // 12: fleetly.identity.v1.RevokeTokenResponse.token:type_name -> fleetly.identity.v1.Token
	38, // 13: fleetly.identity.v1.CreateInvitationResponse.invitation:type_name -> fleetly.identity.v1.Invitation
	38, // 14: fleetly.identity.v1.ListInvitationsResponse.invitations:type_name -> fleetly.identity.v1.Invitation
	2,  // 15: fleetly.identity.v1.AcceptInvitationResponse.user:type_name -> fleetly.identity.v1.User
	45, // 16: fleetly.identity.v1.ListAuditResponse.entries:type_name -> fleetly.identity.v1.AuditEntry
	0,  // 17: fleetly.identity.v1.UsersService.WhoAmI:input_type -> fleetly.identity.v1.WhoAmIRequest
	3,  // 18: fleetly.identity.v1.UsersService.CreateUser:input_type -> fleetly.identity.v1.CreateUserRequest
	5,  // 19: fleetly.identity.v1.UsersService.GetUser:input_type -> fleetly.identity.v1.GetUserRequest
	7,  // 20: fleetly.identity.v1.UsersService.ListUsers:input_type -> fleetly.identity.v1.ListUsersRequest
	9,  // 21: fleetly.identity.v1.UsersService.DeleteUser:input_type -> fleetly.identity.v1.DeleteUserRequest
	12, // 22: fleetly.identity.v1.TeamsService.CreateTeam:input_type -> fleetly.identity.v1.CreateTeamRequest
	14, // 23: fleetly.identity.v1.TeamsService.GetTeam:input_type -> fleetly.identity.v1.GetTeamRequest
	16, // 24: fleetly.identity.v1.TeamsService.ListTeams:input_type -> fleetly.identity.v1.ListTeamsRequest
	18, // 25: fleetly.identity.v1.TeamsService.DeleteTeam:input_type -> fleetly.identity.v1.DeleteTeamRequest
	21, // 26: fleetly.identity.v1.RolesService.CreateRole:input_type -> fleetly.identity.v1.CreateRoleRequest
	23, // 27: fleetly.identity.v1.RolesService.GetRole:input_type -> fleetly.identity.v1.GetRoleRequest
	25, // 28: fleetly.identity.v1.RolesService.ListRoles:input_type -> fleetly.identity.v1.ListRolesRequest
	27, // 29: fleetly.identity.v1.RolesService.DeleteRole:input_type -> fleetly.identity.v1.DeleteRoleRequest
	30, // 30: fleetly.identity.v1.TokensService.CreateToken:input_type -> fleetly.identity.v1.CreateTokenRequest
	32, // 31: fleetly.identity.v1.TokensService.GetToken:input_type -> fleetly.identity.v1.GetTokenRequest
	34, // 32: fleetly.identity.v1.TokensService.ListTokens:input_type -> fleetly.identity.v1.ListTokensRequest
	36, // 33: fleetly.identity.v1.TokensService.RevokeToken:input_type -> fleetly.identity.v1.RevokeTokenRequest
	39, // 34: fleetly.identity.v1.InvitationsService.CreateInvitation:input_type -> fleetly.identity.v1.CreateInvitationRequest
	41, // 35: fleetly.identity.v1.InvitationsService.ListInvitations:input_type -> fleetly.identity.v1.ListInvitationsRequest
	43, // 36: fleetly.identity.v1.InvitationsService.AcceptInvitation:input_type -> fleetly.identity.v1.AcceptInvitationRequest
	46, // 37: fleetly.identity.v1.AuditQueryService.ListAudit:input_type -> fleetly.identity.v1.ListAuditRequest
	1,  // 38: fleetly.identity.v1.UsersService.WhoAmI:output_type -> fleetly.identity.v1.WhoAmIResponse
	4,  // 39: fleetly.identity.v1.UsersService.CreateUser:output_type -> fleetly.identity.v1.CreateUserResponse
	6,  // 40: fleetly.identity.v1.UsersService.GetUser:output_type -> fleetly.identity.v1.GetUserResponse
	8,  // 41: fleetly.identity.v1.UsersService.ListUsers:output_type -> fleetly.identity.v1.ListUsersResponse
	10, // 42: fleetly.identity.v1.UsersService.DeleteUser:output_type -> fleetly.identity.v1.DeleteUserResponse
	13, // 43: fleetly.identity.v1.TeamsService.CreateTeam:output_type -> fleetly.identity.v1.CreateTeamResponse
	15, // 44: fleetly.identity.v1.TeamsService.GetTeam:output_type -> fleetly.identity.v1.GetTeamResponse
	17, // 45: fleetly.identity.v1.TeamsService.ListTeams:output_type -> fleetly.identity.v1.ListTeamsResponse
	19, // 46: fleetly.identity.v1.TeamsService.DeleteTeam:output_type -> fleetly.identity.v1.DeleteTeamResponse
	22, // 47: fleetly.identity.v1.RolesService.CreateRole:output_type -> fleetly.identity.v1.CreateRoleResponse
	24, // 48: fleetly.identity.v1.RolesService.GetRole:output_type -> fleetly.identity.v1.GetRoleResponse
	26, // 49: fleetly.identity.v1.RolesService.ListRoles:output_type -> fleetly.identity.v1.ListRolesResponse
	28, // 50: fleetly.identity.v1.RolesService.DeleteRole:output_type -> fleetly.identity.v1.DeleteRoleResponse
	31, // 51: fleetly.identity.v1.TokensService.CreateToken:output_type -> fleetly.identity.v1.CreateTokenResponse
	33, // 52: fleetly.identity.v1.TokensService.GetToken:output_type -> fleetly.identity.v1.GetTokenResponse
	35, // 53: fleetly.identity.v1.TokensService.ListTokens:output_type -> fleetly.identity.v1.ListTokensResponse
	37, // 54: fleetly.identity.v1.TokensService.RevokeToken:output_type -> fleetly.identity.v1.RevokeTokenResponse
	40, // 55: fleetly.identity.v1.InvitationsService.CreateInvitation:output_type -> fleetly.identity.v1.CreateInvitationResponse
	42, // 56: fleetly.identity.v1.InvitationsService.ListInvitations:output_type -> fleetly.identity.v1.ListInvitationsResponse
	44, // 57: fleetly.identity.v1.InvitationsService.AcceptInvitation:output_type -> fleetly.identity.v1.AcceptInvitationResponse
	47, // 58: fleetly.identity.v1.AuditQueryService.ListAudit:output_type -> fleetly.identity.v1.ListAuditResponse
	38, // [38:59] is the sub-list for method output_type
	17, // [17:38] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_fleetly_identity_v1_identity_proto_init() }
func file_fleetly_identity_v1_identity_proto_init() {
	if File_fleetly_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_identity_v1_identity_proto_rawDesc), len(file_fleetly_identity_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   48,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_fleetly_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_fleetly_identity_v1_identity_proto_depIdxs,
		MessageInfos:      file_fleetly_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_fleetly_identity_v1_identity_proto = out.File
	file_fleetly_identity_v1_identity_proto_goTypes = nil
	file_fleetly_identity_v1_identity_proto_depIdxs = nil
}
